'use strict';
// The AirConsole entries (display/screen.html, controller/controller.html) are
// COMMITTED files generated from the canonical index.html pair — this is the
// gate that keeps them current: an index.html edit that forgets to re-run
// `npm run gen:airconsole` fails here with the regenerated bytes differing.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const PUBLIC = path.join(__dirname, '..', 'public');
const read = (rel) => fs.readFileSync(path.join(PUBLIC, rel), 'utf8');

test('committed AirConsole entries match a fresh generation', async () => {
  const { generateAirconsoleHtml } = await import('../scripts/gen-airconsole-html.mjs');
  const { screenHtml, controllerHtml } = generateAirconsoleHtml();
  assert.equal(read('display/screen.html'), screenHtml,
    'display/screen.html is stale — run `npm run gen:airconsole`');
  assert.equal(read('controller/controller.html'), controllerHtml,
    'controller/controller.html is stale — run `npm run gen:airconsole`');
});

test('the AC entries carry no absolute asset paths', () => {
  // The zip serves from its root with no server — one absolute src/href would
  // 404 only there, the deploy surface nobody tests by hand.
  for (const rel of ['display/screen.html', 'controller/controller.html']) {
    const abs = read(rel).match(/(?:src|href)="\/(?!\/)[^"]*"/g) || [];
    assert.deepEqual(abs, [], `${rel} still references absolute paths`);
  }
});

// The same trap one layer down — a '/assets/…' literal built in JS or CSS — is
// NOT re-checked here. tests/asset-urls.test.js holds that rule for the whole
// tree, and a second copy with its own exemption list is exactly the drift the
// one-source rule exists to stop. Note it is the stricter of the two: it scans
// the dev-only files this zip prunes as well.
