'use strict';
// Bit-exact gate for the deterministic mathlib (engine/math.js — fdlibm
// compiled to WASM). Replays every line of tests/fixtures/math-corpus.jsonl
// and demands identical IEEE-754 bit patterns. The corpus was generated by
// scripts/gen-math-corpus.mjs from the same vendored sources the native C++
// engine links, so this test (here) plus its C++ twin (native/, Milestone 2)
// prove both builds compute identical transcendentals — the foundation that
// makes golden traces platform- and engine-independent.
//
// If this fails after rebuilding the WASM (new emsdk, changed flags), that is
// REAL DRIFT: fix the build, or re-record corpus + all trace fixtures
// together, deliberately.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const CORPUS = path.join(__dirname, 'fixtures', 'math-corpus.jsonl');

const view = new DataView(new ArrayBuffer(8));
function toHex(x) {
  if (Number.isNaN(x)) return 'nan';
  view.setFloat64(0, x);
  return view.getBigUint64(0).toString(16).padStart(16, '0');
}
function fromHex(h) {
  if (h === 'nan') return NaN;
  view.setBigUint64(0, BigInt('0x' + h));
  return view.getFloat64(0);
}

test('mathlib reproduces the conformance corpus bit-for-bit', async () => {
  const dmath = await import('../public/display/engine/math.js');
  const linesRaw = fs.readFileSync(CORPUS, 'utf8').trim().split('\n');
  const header = JSON.parse(linesRaw[0]);
  assert.equal(header.mathlib, dmath.MATHLIB,
    'corpus was generated for a different mathlib build — regenerate with scripts/gen-math-corpus.mjs');
  const lines = linesRaw.slice(1);
  assert.equal(lines.length, header.cases, 'corpus truncated');

  const perFn = {};
  for (const line of lines) {
    const { f, i, o } = JSON.parse(line);
    const got = toHex(dmath[f](...i.map(fromHex)));
    assert.equal(got, o, `${f}(${i.join(', ')}) drifted`);
    perFn[f] = (perFn[f] || 0) + 1;
  }
  for (const f of ['sin', 'cos', 'atan2', 'exp', 'pow', 'hypot'])
    assert.ok(perFn[f] > 100, `corpus is missing meaningful ${f} coverage`);
});

test('round-trip and NaN canonicalization of the hex codec', () => {
  for (const x of [0, -0, 1.5, -1e300, Number.MIN_VALUE, Infinity, -Infinity]) {
    assert.ok(Object.is(fromHex(toHex(x)), x), `codec round-trip ${x}`);
  }
  assert.equal(toHex(NaN), 'nan');
  assert.ok(Number.isNaN(fromHex('nan')));
});
