'use strict';
// Bake the CHOSEN seeds into public/shared/genTracks.js — the resolved waypoints that the
// dependency-free catalogue (public/shared/tracks.js) imports. The generation pipeline lives
// in ./track-gen.mjs; this file just names which seed becomes which track id and writes them.
//
// Workflow for adding tracks:  node scripts/scan-seeds.mjs 1 300   →  pick promising seeds
//   →  add them to SEEDS below  →  node scripts/gen-tracks.mjs  →  register the id in tracks.js
//   →  preview at /?scenario=track&track=<id>
import fs from 'fs';
import path from 'path';
import { bakeSeed, buildTrack } from './track-gen.mjs';
const ROOT = path.join(path.dirname(new URL(import.meta.url).pathname), '..');

// which seed becomes which track id (re-pick by editing this, then re-run)
const SEEDS = { bowtie: 92, pretzel: 13, lasso: 17, cloverleaf: 121 };

const out = {};
for (const [id, seed] of Object.entries(SEEDS)) {
  const wp = bakeSeed(seed); out[id] = wp;
  const t = buildTrack({ waypoints: wp });
  console.log(`${id.padEnd(11)} seed ${seed}  ${wp.length} wp  len ${t.length.toFixed(0)} (~${(t.length * 0.124).toFixed(0)}s)  pillars ${t.pillars.length}  closed ${t.closed}`);
}
const body = Object.entries(out).map(([id, wp]) => `  ${id}: ${JSON.stringify(wp)}`).join(',\n');
const seedNote = Object.entries(SEEDS).map(([id, s]) => `${id}=${s}`).join(', ');
fs.writeFileSync(path.join(ROOT, 'public/shared/genTracks.js'),
  `// GENERATED by scripts/gen-tracks.mjs — DO NOT EDIT BY HAND.\n` +
  `// Resolved waypoints for seeded multi-crossing tracks (solved elevation baked in). Seeds: ${seedNote}.\n` +
  `// Regenerate: node scripts/gen-tracks.mjs\nexport const GEN_TRACKS = {\n${body}\n};\n`);
console.log('wrote public/shared/genTracks.js');
