// Bake the CHOSEN seeds into public/shared/genTracks.js — the resolved waypoints that the
// dependency-free catalogue (public/shared/tracks.js) imports. The generation pipeline lives
// in ./track-gen.mjs; this file just names which {seed, profile} becomes which track id and
// writes them, along with auto-placed furniture (oils/pads/boxes — see placeFurniture) for
// every non-classic track. The classic Backyard four keep their hand-tuned furniture in
// tracks.js, and their bakes must never change (the classic profile is frozen).
//
// Workflow for adding tracks:  node scripts/scan-seeds.mjs <profile> 1 400  →  pick seeds
//   →  add them to SEEDS below  →  node scripts/gen-tracks.mjs  →  register the id in
//   tracks.js (waypoints + furniture from GEN_TRACKS/GEN_FURNITURE, cup, difficulty)
//   →  node scripts/gen-track-schematics.js  →  preview at /?scenario=track&track=<id>
import fs from 'fs';
import path from 'path';
import { bakeSeed, buildTrack, placeFurniture, PROFILES } from './track-gen.mjs';
const ROOT = path.join(path.dirname(new URL(import.meta.url).pathname), '..');

// which {seed, profile} becomes which track id (re-pick by editing this, then re-run)
// User-picked rosters (audition round of 2026-07-03; see gallery-tracks.html).
const SEEDS = {
  // Beach Cup (Easy)
  tidepool:   { seed: 88,  profile: 'easy' },
  cove:       { seed: 250, profile: 'easy' },
  driftwood:  { seed: 138, profile: 'easy' },
  riptide:    { seed: 330, profile: 'easy' },
  // Backyard Cup (middle) — pretzel/cloverleaf are original classic seeds re-baked
  // through the decorated mid profile (same plans/crossings — mid shares classic's
  // grammar). The frozen `classic` profile stays in track-gen as provenance.
  ribbon:     { seed: 128, profile: 'mid' },
  pretzel:    { seed: 13,  profile: 'mid' },
  tangle:     { seed: 372, profile: 'mid' },
  cloverleaf: { seed: 121, profile: 'mid' },
  // Canyon Cup (Hard)
  wash:       { seed: 193, profile: 'hard' },
  gulch:      { seed: 550, profile: 'hard' },
  crag:       { seed: 276, profile: 'hard' },
  sidewinder: { seed: 62,  profile: 'hard' },
};

const out = {}, furn = {};
for (const [id, { seed, profile }] of Object.entries(SEEDS)) {
  const wp = bakeSeed(seed, profile); out[id] = wp;
  const t = buildTrack({ waypoints: wp });
  if (profile !== 'classic') furn[id] = placeFurniture(t, { oils: PROFILES[profile].oilCount });
  console.log(`${id.padEnd(11)} ${profile.padEnd(7)} seed ${String(seed).padStart(3)}  ${wp.length} wp  len ${t.length.toFixed(0)} (~${(t.length * 0.124).toFixed(0)}s)  pillars ${t.pillars.length}  hills ${t.hills.length}  closed ${t.closed}`);
}
const body = Object.entries(out).map(([id, wp]) => `  ${id}: ${JSON.stringify(wp)}`).join(',\n');
const furnBody = Object.entries(furn).map(([id, f]) => `  ${id}: ${JSON.stringify(f)}`).join(',\n');
const seedNote = Object.entries(SEEDS).map(([id, s]) => `${id}=${s.seed}(${s.profile})`).join(', ');
fs.writeFileSync(path.join(ROOT, 'public/shared/genTracks.js'),
  `// GENERATED by scripts/gen-tracks.mjs — DO NOT EDIT BY HAND.\n` +
  `// Resolved waypoints for seeded generated tracks (solved elevation + decoration baked in),\n` +
  `// plus auto-placed furniture (placeFurniture) for the non-classic ones.\n` +
  `// Seeds: ${seedNote}.\n` +
  `// Regenerate: node scripts/gen-tracks.mjs\nexport const GEN_TRACKS = {\n${body}\n};\n\n` +
  `export const GEN_FURNITURE = {\n${furnBody}\n};\n`);
console.log('wrote public/shared/genTracks.js');
