// GENERATED by scripts/gen-jni.mjs — do not edit.
//
// The JNI half of the Android shell's bridge. Its Kotlin twin is
// shells/androidtv/app/src/main/kotlin/games/couchpad/tinytrack/Ttp.kt,
// emitted from the same parse in the same run, so the two cannot disagree
// about a signature. The rules both obey are documented in the generator.
//
// STRINGS CROSS AS byte[], NEVER AS jstring. NewStringUTF and
// GetStringUTFChars speak MODIFIED UTF-8, in which a non-BMP character is a
// surrogate pair of three-byte sequences and U+0000 is two bytes — neither
// is UTF-8, and both would corrupt a payload silently. The controller's name
// field is free text off a phone and reaches every one of these, and
// tests/fixtures/json-escape-corpus.jsonl exists because that boundary had
// no coverage once already.

#include <jni.h>
#include <string.h>
#include <vector>

#include "ttp_runtime.h"
#include "ttp_party.h"
#include "ttp_net.h"
#include "ttp_race.h"
#include "ttp_ui.h"
#include "ttp_audio.h"
#include "ttp_display.h"
#include "ttp_theme.h"
#include "ttp_glb.h"
#include "ttp_perf.h"
#include "ttp_error.h"
#include "ttp_hud.h"

namespace {

// A ceiling on the comma count, so a corrupt names string cannot make
// ttpProfileBytes() advertise an unbounded buffer.
constexpr int TTP_PROFILE_MAX = 64;

// A jbyteArray as a NUL-terminated C string. Null in, null out: every ABI
// here spells "absent" as a null pointer, and an OrNull parameter must be
// able to receive one.
struct CStr {
    std::vector<char> buf;
    bool null = true;
    CStr(JNIEnv* env, jbyteArray a) {
        if (!a) return;
        null = false;
        const jsize n = env->GetArrayLength(a);
        buf.resize((size_t) n + 1);
        if (n) env->GetByteArrayRegion(a, 0, n, (jbyte*) buf.data());
        buf[(size_t) n] = 0;
    }
    const char* get() const { return null ? nullptr : buf.data(); }
};

// A returned scratch const char* as a fresh byte[]. Copies at the call site,
// which is the whole point: the pointer is only valid until the next ttp_*
// call on that handle, and a Kotlin caller has no way to honour that.
jbyteArray toBytes(JNIEnv* env, const char* s) {
    if (!s) return nullptr;
    const size_t n = strlen(s);
    jbyteArray a = env->NewByteArray((jsize) n);
    if (a && n) env->SetByteArrayRegion(a, 0, (jsize) n, (const jbyte*) s);
    return a;
}

jbyteArray toBytes(JNIEnv* env, const uint8_t* p, uint32_t n) {
    if (!p) return nullptr;
    jbyteArray a = env->NewByteArray((jsize) n);
    if (a && n) env->SetByteArrayRegion(a, 0, (jsize) n, (const jbyte*) p);
    return a;
}

// The profile array's length is NOT a constant the ABI states: it is the
// comma count of ttp_display_profile_names() plus one. Capacity is the only
// bound a Kotlin reader has, so a fixed cap here would advertise bytes past
// the end of the renderer's array — readable, wrong, and silent.
size_t ttpProfileBytes() {
    const char* names = ttp_display_profile_names();
    if (!names || !*names) return 0;
    size_t n = 1;
    for (const char* p = names; *p; ++p) if (*p == ',') n++;
    if (n > (size_t) TTP_PROFILE_MAX) n = (size_t) TTP_PROFILE_MAX;
    return n * sizeof(double);
}

size_t ttpHudBlockBytes(const TtpHudBlock* b) {
    return b ? sizeof(TtpHudBlock) + (size_t) b->slotCount * b->stride : 0;
}
size_t ttpAudioBlockBytes(const TtpAudioBlock* b) {
    return b ? sizeof(TtpAudioBlock) + (size_t) b->count * b->stride : 0;
}

void n_ttp_add_bot(JNIEnv* env, jclass, jint a0, jbyteArray a1, jdouble a2, jdouble a3, jint a4, jbyteArray a5) {
    CStr s1(env, a1);
    CStr s5(env, a5);
    ttp_add_bot((int) a0, s1.get(), (double) a2, (double) a3, (uint32_t) a4, s5.get());
}

void n_ttp_add_human(JNIEnv* env, jclass, jint a0, jbyteArray a1, jbyteArray a2) {
    CStr s1(env, a1);
    CStr s2(env, a2);
    ttp_add_human((int) a0, s1.get(), s2.get());
}

void n_ttp_audio_bind(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_audio_bind((int) a0);
}

jbyteArray n_ttp_audio_cue_id(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_audio_cue_id((int) a0));
}

jobject n_ttp_audio_drain(JNIEnv* env, jclass) {
    const auto* p = ttp_audio_drain();
    if (!p) return nullptr;
    return env->NewDirectByteBuffer((void*) p, (jlong) (ttpAudioBlockBytes(p)));
}

void n_ttp_audio_frame(JNIEnv* env, jclass, jdouble a0) {
    (void) env;
    ttp_audio_frame((double) a0);
}

void n_ttp_audio_music(JNIEnv* env, jclass, jint a0, jbyteArray a1) {
    CStr s1(env, a1);
    ttp_audio_music((int) a0, s1.get());
}

void n_ttp_audio_roster(JNIEnv* env, jclass, jint a0, jint a1) {
    (void) env;
    ttp_audio_roster((int) a0, (int) a1);
}

jbyteArray n_ttp_audio_song_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_audio_song_json((int) a0));
}

void n_ttp_audio_stop_car(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    ttp_audio_stop_car(s0.get());
}

void n_ttp_audio_stop_voices(JNIEnv* env, jclass) {
    (void) env;
    ttp_audio_stop_voices();
}

jbyteArray n_ttp_blob_plan_json(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_blob_plan_json(s0.get()));
}

jint n_ttp_car_finished(JNIEnv* env, jclass, jint a0, jbyteArray a1) {
    CStr s1(env, a1);
    return (jint) ttp_car_finished((int) a0, s1.get());
}

jbyteArray n_ttp_car_ids_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_car_ids_json((int) a0));
}

jint n_ttp_car_world_pos(JNIEnv* env, jclass, jint a0, jbyteArray a1, jdoubleArray outArr) {
    CStr s1(env, a1);
    double outv[3] = { 0 };
    const jint rc = (jint) ttp_car_world_pos((int) a0, s1.get(), outv);
    if (rc && outArr && env->GetArrayLength(outArr) >= 3) env->SetDoubleArrayRegion(outArr, 0, 3, outv);
    return rc;
}

void n_ttp_display_antialias(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_antialias((int) a0);
}

jint n_ttp_display_asset(JNIEnv* env, jclass, jbyteArray a0, jbyteArray bytes) {
    CStr s0(env, a0);
    const jsize n = bytes ? env->GetArrayLength(bytes) : 0;
    std::vector<uint8_t> b((size_t) n);
    if (n) env->GetByteArrayRegion(bytes, 0, n, (jbyte*) b.data());
    return (jint) ttp_display_asset(s0.get(), b.data(), (uint32_t) n);
}

jbyteArray n_ttp_display_bake_export(JNIEnv* env, jclass) {
    uint32_t outLen = 0;
    const uint8_t* p = ttp_display_bake_export(&outLen);
    return toBytes(env, p, outLen);
}

jint n_ttp_display_bake_import(JNIEnv* env, jclass, jbyteArray bytes) {
    const jsize n = bytes ? env->GetArrayLength(bytes) : 0;
    std::vector<uint8_t> b((size_t) n);
    if (n) env->GetByteArrayRegion(bytes, 0, n, (jbyte*) b.data());
    return (jint) ttp_display_bake_import(b.data(), (uint32_t) n);
}

jbyteArray n_ttp_display_bake_key(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_display_bake_key(s0.get()));
}

void n_ttp_display_bench(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    ttp_display_bench(s0.get());
}

void n_ttp_display_bind(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_bind((int) a0);
}

void n_ttp_display_biome(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    ttp_display_biome(s0.get());
}

jint n_ttp_display_build(JNIEnv* env, jclass, jbyteArray a0, jbyteArray a1) {
    CStr s0(env, a0);
    CStr s1(env, a1);
    return (jint) ttp_display_build(s0.get(), s1.get());
}

void n_ttp_display_burst(JNIEnv* env, jclass, jbyteArray a0, jdouble a1, jdouble a2) {
    CStr s0(env, a0);
    ttp_display_burst(s0.get(), (double) a1, (double) a2);
}

void n_ttp_display_camera(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_camera((int) a0);
}

void n_ttp_display_cell_cards(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_cell_cards((uint32_t) a0);
}

jint n_ttp_display_cell_rects(JNIEnv* env, jclass, jfloatArray outArr, jint maxCells) {
    if (!outArr) return 0;
    const jint cap = env->GetArrayLength(outArr) / 4;
    const jint want = maxCells < cap ? maxCells : cap;
    std::vector<float> tmp((size_t) (want > 0 ? want : 0) * 4, 0.0f);
    const jint n = (jint) ttp_display_cell_rects(tmp.data(), (int) want);
    if (n > 0) env->SetFloatArrayRegion(outArr, 0, n * 4, tmp.data());
    return n;
}

void n_ttp_display_cells(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    ttp_display_cells(s0.get());
}

jbyteArray n_ttp_display_debug_decals(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_display_debug_decals());
}

void n_ttp_display_debug_features(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_debug_features((unsigned int) a0);
}

void n_ttp_display_debug_force_mask_layer(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_debug_force_mask_layer((int) a0);
}

void n_ttp_display_debug_hide_cars(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_debug_hide_cars((int) a0);
}

void n_ttp_display_debug_wipe_skids(JNIEnv* env, jclass) {
    (void) env;
    ttp_display_debug_wipe_skids();
}

void n_ttp_display_destroy(JNIEnv* env, jclass) {
    (void) env;
    ttp_display_destroy();
}

void n_ttp_display_dividers(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_dividers((int) a0);
}

void n_ttp_display_drain(JNIEnv* env, jclass) {
    (void) env;
    ttp_display_drain();
}

void n_ttp_display_fog(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_fog((int) a0);
}

jint n_ttp_display_frame(JNIEnv* env, jclass, jdouble a0) {
    (void) env;
    return (jint) ttp_display_frame((double) a0);
}

jdouble n_ttp_display_gpu_ms(JNIEnv* env, jclass) {
    (void) env;
    return (jdouble) ttp_display_gpu_ms();
}

void n_ttp_display_hold(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_hold((int) a0);
}

jobject n_ttp_display_hud(JNIEnv* env, jclass) {
    const auto* p = ttp_display_hud();
    if (!p) return nullptr;
    return env->NewDirectByteBuffer((void*) p, (jlong) (ttpHudBlockBytes(p)));
}

void n_ttp_display_kit_field(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_kit_field((int) a0);
}

jbyteArray n_ttp_display_kit_field_layout(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_display_kit_field_layout());
}

void n_ttp_display_look(JNIEnv* env, jclass, jdouble a0, jdouble a1, jdouble a2, jdouble a3, jdouble a4, jdouble a5) {
    (void) env;
    ttp_display_look((double) a0, (double) a1, (double) a2, (double) a3, (double) a4, (double) a5);
}

void n_ttp_display_model_variant(JNIEnv* env, jclass, jbyteArray a0, jint a1) {
    CStr s0(env, a0);
    ttp_display_model_variant(s0.get(), (int) a1);
}

void n_ttp_display_multiview(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_multiview((int) a0);
}

jobject n_ttp_display_profile(JNIEnv* env, jclass) {
    const auto* p = ttp_display_profile();
    if (!p) return nullptr;
    return env->NewDirectByteBuffer((void*) p, (jlong) (ttpProfileBytes()));
}

jbyteArray n_ttp_display_profile_names(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_display_profile_names());
}

void n_ttp_display_release(JNIEnv* env, jclass) {
    (void) env;
    ttp_display_release();
}

jint n_ttp_display_reroster(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return (jint) ttp_display_reroster(s0.get());
}

void n_ttp_display_resize(JNIEnv* env, jclass, jint a0, jint a1) {
    (void) env;
    ttp_display_resize((uint32_t) a0, (uint32_t) a1);
}

jdouble n_ttp_display_scale_panel_ms(JNIEnv* env, jclass) {
    (void) env;
    return (jdouble) ttp_display_scale_panel_ms();
}

jint n_ttp_display_scale_poll(JNIEnv* env, jclass, jdouble a0, jdouble a1, jdouble a2, jdouble a3, jdouble a4, jdoubleArray outArr) {
    double outv[2] = { 0 };
    const jint rc = (jint) ttp_display_scale_poll((double) a0, (double) a1, (double) a2, (double) a3, (double) a4, outv);
    if (rc && outArr && env->GetArrayLength(outArr) >= 2) env->SetDoubleArrayRegion(outArr, 0, 2, outv);
    return rc;
}

void n_ttp_display_scale_scene(JNIEnv* env, jclass, jdouble a0) {
    (void) env;
    ttp_display_scale_scene((double) a0);
}

void n_ttp_display_shadows(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_shadows((int) a0);
}

void n_ttp_display_showcase(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_display_showcase((int) a0);
}

jbyteArray n_ttp_display_slot_ids_json(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_display_slot_ids_json());
}

void n_ttp_dispose(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_dispose((int) a0);
}

jbyteArray n_ttp_events_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_events_json((int) a0));
}

void n_ttp_fast_forward(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_fast_forward((int) a0);
}

void n_ttp_force_finish(JNIEnv* env, jclass, jint a0, jbyteArray a1, jdouble a2) {
    CStr s1(env, a1);
    ttp_force_finish((int) a0, s1.get(), (double) a2);
}

jint n_ttp_force_remove_car(JNIEnv* env, jclass, jint a0, jbyteArray a1) {
    CStr s1(env, a1);
    return (jint) ttp_force_remove_car((int) a0, s1.get());
}

jdouble n_ttp_framing_backoff_ms(JNIEnv* env, jclass, jdouble a0) {
    (void) env;
    return (jdouble) ttp_framing_backoff_ms((double) a0);
}

jbyteArray n_ttp_framing_classify(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_framing_classify(s0.get()));
}

jbyteArray n_ttp_framing_close_outcome(JNIEnv* env, jclass, jint a0, jdouble a1, jdouble a2, jdouble a3, jint a4) {
    (void) env;
    return toBytes(env, ttp_framing_close_outcome((int) a0, (double) a1, (double) a2, (double) a3, (int) a4));
}

jbyteArray n_ttp_framing_encode_broadcast(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_framing_encode_broadcast(s0.get()));
}

jbyteArray n_ttp_framing_encode_close_room(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_framing_encode_close_room());
}

jbyteArray n_ttp_framing_encode_create(JNIEnv* env, jclass, jbyteArray a0, jdouble a1, jbyteArray a2) {
    CStr s0(env, a0);
    CStr s2(env, a2);
    return toBytes(env, ttp_framing_encode_create(s0.get(), (double) a1, s2.get()));
}

jbyteArray n_ttp_framing_encode_join(JNIEnv* env, jclass, jbyteArray a0, jbyteArray a1) {
    CStr s0(env, a0);
    CStr s1(env, a1);
    return toBytes(env, ttp_framing_encode_join(s0.get(), s1.get()));
}

jbyteArray n_ttp_framing_encode_send_to(JNIEnv* env, jclass, jbyteArray a0, jbyteArray a1) {
    CStr s0(env, a0);
    CStr s1(env, a1);
    return toBytes(env, ttp_framing_encode_send_to(s0.get(), s1.get()));
}

jbyteArray n_ttp_framing_encode_set_state(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_framing_encode_set_state(s0.get()));
}

jdouble n_ttp_framing_max_reconnect_attempts(JNIEnv* env, jclass) {
    (void) env;
    return (jdouble) ttp_framing_max_reconnect_attempts();
}

jbyteArray n_ttp_framing_pin_url(JNIEnv* env, jclass, jbyteArray a0, jbyteArray a1, jbyteArray a2) {
    CStr s0(env, a0);
    CStr s1(env, a1);
    CStr s2(env, a2);
    return toBytes(env, ttp_framing_pin_url(s0.get(), s1.get(), s2.get()));
}

jdouble n_ttp_get_steer_expo(JNIEnv* env, jclass) {
    (void) env;
    return (jdouble) ttp_get_steer_expo();
}

jbyteArray n_ttp_glb_ghost(JNIEnv* env, jclass, jbyteArray bytes) {
    const jsize n = bytes ? env->GetArrayLength(bytes) : 0;
    std::vector<uint8_t> b((size_t) n);
    if (n) env->GetByteArrayRegion(bytes, 0, n, (jbyte*) b.data());
    uint32_t outLen = 0;
    const uint8_t* p = ttp_glb_ghost(b.data(), (uint32_t) n, &outLen);
    return toBytes(env, p, outLen);
}

jbyteArray n_ttp_glb_image_uris(JNIEnv* env, jclass, jbyteArray bytes) {
    const jsize n = bytes ? env->GetArrayLength(bytes) : 0;
    std::vector<uint8_t> b((size_t) n);
    if (n) env->GetByteArrayRegion(bytes, 0, n, (jbyte*) b.data());
    return toBytes(env, ttp_glb_image_uris(b.data(), (uint32_t) n));
}

void n_ttp_gp_advance(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_gp_advance((int) a0);
}

void n_ttp_gp_apply_race(JNIEnv* env, jclass, jint a0, jbyteArray a1, jbyteArray a2, jbyteArray a3) {
    CStr s1(env, a1);
    CStr s2(env, a2);
    CStr s3(env, a3);
    ttp_gp_apply_race((int) a0, s1.get(), s2.get(), s3.get());
}

jint n_ttp_gp_create(JNIEnv* env, jclass, jbyteArray a0, jint a1) {
    CStr s0(env, a0);
    return (jint) ttp_gp_create(s0.get(), (int) a1);
}

void n_ttp_gp_dispose(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_gp_dispose((int) a0);
}

void n_ttp_gp_rekey(JNIEnv* env, jclass, jint a0, jbyteArray a1, jbyteArray a2) {
    CStr s1(env, a1);
    CStr s2(env, a2);
    ttp_gp_rekey((int) a0, s1.get(), s2.get());
}

jbyteArray n_ttp_gp_state_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_gp_state_json((int) a0));
}

jint n_ttp_has_car(JNIEnv* env, jclass, jint a0, jbyteArray a1) {
    CStr s1(env, a1);
    return (jint) ttp_has_car((int) a0, s1.get());
}

jbyteArray n_ttp_item_id(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_item_id((int) a0));
}

jbyteArray n_ttp_last_error(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_last_error());
}

jint n_ttp_link_create(JNIEnv* env, jclass) {
    (void) env;
    return (jint) ttp_link_create();
}

void n_ttp_link_dispose(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_link_dispose((int) a0);
}

jbyteArray n_ttp_link_enqueue(JNIEnv* env, jclass, jint a0, jbyteArray a1, jdouble a2) {
    CStr s1(env, a1);
    return toBytes(env, ttp_link_enqueue((int) a0, s1.get(), (double) a2));
}

jbyteArray n_ttp_link_idle(JNIEnv* env, jclass, jint a0, jdouble a1) {
    (void) env;
    return toBytes(env, ttp_link_idle((int) a0, (double) a1));
}

jbyteArray n_ttp_link_inbound(JNIEnv* env, jclass, jint a0, jbyteArray a1, jdouble a2) {
    CStr s1(env, a1);
    return toBytes(env, ttp_link_inbound((int) a0, s1.get(), (double) a2));
}

jbyteArray n_ttp_link_send_tick(JNIEnv* env, jclass, jint a0, jdouble a1) {
    (void) env;
    return toBytes(env, ttp_link_send_tick((int) a0, (double) a1));
}

void n_ttp_link_set_channel_open(JNIEnv* env, jclass, jint a0, jint a1) {
    (void) env;
    ttp_link_set_channel_open((int) a0, (int) a1);
}

jbyteArray n_ttp_link_stats_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_link_stats_json((int) a0));
}

jbyteArray n_ttp_net_claim_url(JNIEnv* env, jclass, jbyteArray a0, jdouble a1) {
    CStr s0(env, a0);
    return toBytes(env, ttp_net_claim_url(s0.get(), (double) a1));
}

jbyteArray n_ttp_net_clean_name(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_net_clean_name(s0.get()));
}

void n_ttp_net_clear_pick(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_net_clear_pick((int) a0);
}

jint n_ttp_net_configure(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return (jint) ttp_net_configure(s0.get());
}

jbyteArray n_ttp_net_controller_action(JNIEnv* env, jclass, jint a0, jint a1, jbyteArray a2, jbyteArray a3) {
    CStr s2(env, a2);
    CStr s3(env, a3);
    return toBytes(env, ttp_net_controller_action((int) a0, (int) a1, s2.get(), s3.get()));
}

jbyteArray n_ttp_net_controller_url_template(JNIEnv* env, jclass, jbyteArray a0, jbyteArray a1) {
    CStr s0(env, a0);
    CStr s1(env, a1);
    return toBytes(env, ttp_net_controller_url_template(s0.get(), s1.get()));
}

jbyteArray n_ttp_net_create_timeout_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_net_create_timeout_json((int) a0));
}

jbyteArray n_ttp_net_effect_ops_json(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_net_effect_ops_json());
}

jbyteArray n_ttp_net_host_change_apply_json(JNIEnv* env, jclass, jint a0, jbyteArray a1) {
    CStr s1(env, a1);
    return toBytes(env, ttp_net_host_change_apply_json((int) a0, s1.get()));
}

void n_ttp_net_init_pick(JNIEnv* env, jclass, jint a0, jbyteArray a1, jint a2, jdouble a3) {
    CStr s1(env, a1);
    ttp_net_init_pick((int) a0, s1.get(), (int) a2, (double) a3);
}

jbyteArray n_ttp_net_join_url(JNIEnv* env, jclass, jbyteArray a0, jbyteArray a1, jbyteArray a2, jbyteArray a3) {
    CStr s0(env, a0);
    CStr s1(env, a1);
    CStr s2(env, a2);
    CStr s3(env, a3);
    return toBytes(env, ttp_net_join_url(s0.get(), s1.get(), s2.get(), s3.get()));
}

jbyteArray n_ttp_net_liveness_json(JNIEnv* env, jclass, jint a0, jint a1, jdouble a2) {
    (void) env;
    return toBytes(env, ttp_net_liveness_json((int) a0, (int) a1, (double) a2));
}

jbyteArray n_ttp_net_lobby_frame(JNIEnv* env, jclass, jint a0, jint a1, jbyteArray a2) {
    CStr s2(env, a2);
    return toBytes(env, ttp_net_lobby_frame((int) a0, (int) a1, s2.get()));
}

jbyteArray n_ttp_net_on_close_json(JNIEnv* env, jclass, jint a0, jint a1) {
    (void) env;
    return toBytes(env, ttp_net_on_close_json((int) a0, (int) a1));
}

jbyteArray n_ttp_net_on_open_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_net_on_open_json((int) a0));
}

jbyteArray n_ttp_net_on_peer_message_json(JNIEnv* env, jclass, jint a0, jint a1, jbyteArray a2, jbyteArray a3, jint a4, jdouble a5) {
    CStr s2(env, a2);
    CStr s3(env, a3);
    return toBytes(env, ttp_net_on_peer_message_json((int) a0, (int) a1, s2.get(), s3.get(), (int) a4, (double) a5));
}

jbyteArray n_ttp_net_on_protocol_json(JNIEnv* env, jclass, jint a0, jbyteArray a1, jbyteArray a2, jdouble a3) {
    CStr s1(env, a1);
    CStr s2(env, a2);
    return toBytes(env, ttp_net_on_protocol_json((int) a0, s1.get(), s2.get(), (double) a3));
}

jbyteArray n_ttp_net_on_seen_json(JNIEnv* env, jclass, jint a0, jbyteArray a1, jdouble a2) {
    CStr s1(env, a1);
    return toBytes(env, ttp_net_on_seen_json((int) a0, s1.get(), (double) a2));
}

jbyteArray n_ttp_net_pick_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_net_pick_json((int) a0));
}

jbyteArray n_ttp_net_reconnect_card_json(JNIEnv* env, jclass, jbyteArray a0, jbyteArray a1) {
    CStr s0(env, a0);
    CStr s1(env, a1);
    return toBytes(env, ttp_net_reconnect_card_json(s0.get(), s1.get()));
}

void n_ttp_net_restore_room(JNIEnv* env, jclass, jint a0, jbyteArray a1, jbyteArray a2) {
    CStr s1(env, a1);
    CStr s2(env, a2);
    ttp_net_restore_room((int) a0, s1.get(), s2.get());
}

jbyteArray n_ttp_net_set_track_json(JNIEnv* env, jclass, jint a0, jbyteArray a1) {
    CStr s1(env, a1);
    return toBytes(env, ttp_net_set_track_json((int) a0, s1.get()));
}

jbyteArray n_ttp_net_state_change_apply_json(JNIEnv* env, jclass, jint a0, jbyteArray a1, jdouble a2) {
    CStr s1(env, a1);
    return toBytes(env, ttp_net_state_change_apply_json((int) a0, s1.get(), (double) a2));
}

jbyteArray n_ttp_party_version(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_party_version());
}

void n_ttp_pause(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_pause((int) a0);
}

jint n_ttp_paused(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return (jint) ttp_paused((int) a0);
}

void n_ttp_perf_pacing(JNIEnv* env, jclass, jdouble a0, jint a1) {
    (void) env;
    ttp_perf_pacing((double) a0, (int) a1);
}

jbyteArray n_ttp_perf_readout_json(JNIEnv* env, jclass, jint a0, jint a1, jint a2, jdouble a3, jbyteArray a4) {
    CStr s4(env, a4);
    return toBytes(env, ttp_perf_readout_json((int) a0, (int) a1, (int) a2, (double) a3, s4.get()));
}

void n_ttp_perf_reset(JNIEnv* env, jclass) {
    (void) env;
    ttp_perf_reset();
}

void n_ttp_perf_sample(JNIEnv* env, jclass, jdouble a0, jdouble a1, jint a2, jdouble a3, jdouble a4) {
    (void) env;
    ttp_perf_sample((double) a0, (double) a1, (int) a2, (double) a3, (double) a4);
}

jint n_ttp_process_input(JNIEnv* env, jclass, jint a0, jbyteArray a1, jint a2, jdouble a3, jdouble a4, jdouble a5) {
    CStr s1(env, a1);
    return (jint) ttp_process_input((int) a0, s1.get(), (int) a2, (double) a3, (double) a4, (double) a5);
}

jbyteArray n_ttp_protocol_manifest_json(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_protocol_manifest_json());
}

jbyteArray n_ttp_race_advance_live_json(JNIEnv* env, jclass, jint a0, jint a1, jdouble a2, jdouble a3, jbyteArray a4, jbyteArray a5) {
    CStr s4(env, a4);
    CStr s5(env, a5);
    return toBytes(env, ttp_race_advance_live_json((int) a0, (int) a1, (double) a2, (double) a3, s4.get(), s5.get()));
}

jbyteArray n_ttp_race_auto_pause_live_json(JNIEnv* env, jclass, jint a0, jint a1, jint a2) {
    (void) env;
    return toBytes(env, ttp_race_auto_pause_live_json((int) a0, (int) a1, (int) a2));
}

void n_ttp_race_autopilot_players(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_race_autopilot_players((int) a0);
}

jbyteArray n_ttp_race_bench_field_json(JNIEnv* env, jclass, jbyteArray a0, jint a1, jdouble a2) {
    CStr s0(env, a0);
    return toBytes(env, ttp_race_bench_field_json(s0.get(), (int) a1, (double) a2));
}

jint n_ttp_race_configure(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return (jint) ttp_race_configure(s0.get());
}

jint n_ttp_race_countdown_ready(JNIEnv* env, jclass, jint a0, jint a1, jdouble a2) {
    (void) env;
    return (jint) ttp_race_countdown_ready((int) a0, (int) a1, (double) a2);
}

jbyteArray n_ttp_race_demo_live_json(JNIEnv* env, jclass, jint a0, jbyteArray a1, jbyteArray a2) {
    CStr s1(env, a1);
    CStr s2(env, a2);
    return toBytes(env, ttp_race_demo_live_json((int) a0, s1.get(), s2.get()));
}

jbyteArray n_ttp_race_effect_ops_json(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_race_effect_ops_json());
}

jbyteArray n_ttp_race_end_party_json(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_race_end_party_json());
}

jbyteArray n_ttp_race_events_live_json(JNIEnv* env, jclass, jint a0, jint a1, jbyteArray a2, jint a3, jint a4, jdouble a5, jdouble a6, jdouble a7) {
    CStr s2(env, a2);
    return toBytes(env, ttp_race_events_live_json((int) a0, (int) a1, s2.get(), (int) a3, (int) a4, (double) a5, (double) a6, (double) a7));
}

jbyteArray n_ttp_race_forfeit_live_json(JNIEnv* env, jclass, jint a0, jbyteArray a1) {
    CStr s1(env, a1);
    return toBytes(env, ttp_race_forfeit_live_json((int) a0, s1.get()));
}

jdouble n_ttp_race_intermission_ms(JNIEnv* env, jclass) {
    (void) env;
    return (jdouble) ttp_race_intermission_ms();
}

jbyteArray n_ttp_race_pause_live_json(JNIEnv* env, jclass, jint a0, jint a1, jint a2, jint a3, jint a4) {
    (void) env;
    return toBytes(env, ttp_race_pause_live_json((int) a0, (int) a1, (int) a2, (int) a3, (int) a4));
}

jbyteArray n_ttp_race_personas_json(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_race_personas_json());
}

jbyteArray n_ttp_race_rekey_live_json(JNIEnv* env, jclass, jint a0, jint a1, jbyteArray a2, jbyteArray a3) {
    CStr s2(env, a2);
    CStr s3(env, a3);
    return toBytes(env, ttp_race_rekey_live_json((int) a0, (int) a1, s2.get(), s3.get()));
}

jdouble n_ttp_race_results_failsafe_ms(JNIEnv* env, jclass) {
    (void) env;
    return (jdouble) ttp_race_results_failsafe_ms();
}

jbyteArray n_ttp_race_resume_live_json(JNIEnv* env, jclass, jint a0, jint a1, jint a2, jint a3, jint a4) {
    (void) env;
    return toBytes(env, ttp_race_resume_live_json((int) a0, (int) a1, (int) a2, (int) a3, (int) a4));
}

jbyteArray n_ttp_race_return_live_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_race_return_live_json((int) a0));
}

jbyteArray n_ttp_race_series_state_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_race_series_state_json((int) a0));
}

jbyteArray n_ttp_race_start_live_json(JNIEnv* env, jclass, jint a0, jint a1, jdouble a2, jdouble a3, jbyteArray a4, jbyteArray a5) {
    CStr s4(env, a4);
    CStr s5(env, a5);
    return toBytes(env, ttp_race_start_live_json((int) a0, (int) a1, (double) a2, (double) a3, s4.get(), s5.get()));
}

jint n_ttp_racing(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return (jint) ttp_racing((int) a0);
}

jint n_ttp_rekey_car(JNIEnv* env, jclass, jint a0, jbyteArray a1, jbyteArray a2) {
    CStr s1(env, a1);
    CStr s2(env, a2);
    return (jint) ttp_rekey_car((int) a0, s1.get(), s2.get());
}

jbyteArray n_ttp_results_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_results_json((int) a0));
}

void n_ttp_resume(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_resume((int) a0);
}

jbyteArray n_ttp_room_add_player(JNIEnv* env, jclass, jint a0, jbyteArray a1, jbyteArray a2) {
    CStr s1(env, a1);
    CStr s2(env, a2);
    return toBytes(env, ttp_room_add_player((int) a0, s1.get(), s2.get()));
}

jint n_ttp_room_create(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return (jint) ttp_room_create(s0.get());
}

void n_ttp_room_dispose(JNIEnv* env, jclass, jint a0) {
    (void) env;
    ttp_room_dispose((int) a0);
}

jbyteArray n_ttp_room_events_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_room_events_json((int) a0));
}

jbyteArray n_ttp_room_host_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_room_host_json((int) a0));
}

jbyteArray n_ttp_room_list_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_room_list_json((int) a0));
}

jint n_ttp_room_set_field(JNIEnv* env, jclass, jint a0, jbyteArray a1, jbyteArray a2, jbyteArray a3) {
    CStr s1(env, a1);
    CStr s2(env, a2);
    CStr s3(env, a3);
    return (jint) ttp_room_set_field((int) a0, s1.get(), s2.get(), s3.get());
}

void n_ttp_room_set_liveness_enabled(JNIEnv* env, jclass, jint a0, jint a1) {
    (void) env;
    ttp_room_set_liveness_enabled((int) a0, (int) a1);
}

void n_ttp_room_set_master(JNIEnv* env, jclass, jint a0, jbyteArray a1) {
    CStr s1(env, a1);
    ttp_room_set_master((int) a0, s1.get());
}

jbyteArray n_ttp_room_state(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_room_state((int) a0));
}

jint n_ttp_room_transition_to(JNIEnv* env, jclass, jint a0, jbyteArray a1) {
    CStr s1(env, a1);
    return (jint) ttp_room_transition_to((int) a0, s1.get());
}

jbyteArray n_ttp_schematic_pack(JNIEnv* env, jclass, jbyteArray a0, jdouble a1) {
    CStr s0(env, a0);
    return toBytes(env, ttp_schematic_pack(s0.get(), (double) a1));
}

jbyteArray n_ttp_schematic_points_json(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_schematic_points_json(s0.get()));
}

jint n_ttp_schematic_view_size(JNIEnv* env, jclass) {
    (void) env;
    return (jint) ttp_schematic_view_size();
}

jint n_ttp_session_begin(JNIEnv* env, jclass, jbyteArray a0, jint a1, jint a2, jbyteArray a3) {
    CStr s0(env, a0);
    CStr s3(env, a3);
    return (jint) ttp_session_begin(s0.get(), (uint32_t) a1, (int) a2, s3.get());
}

jint n_ttp_session_begin_field(JNIEnv* env, jclass, jbyteArray a0, jint a1, jint a2, jbyteArray a3, jbyteArray a4, jbyteArray a5) {
    CStr s0(env, a0);
    CStr s3(env, a3);
    CStr s4(env, a4);
    CStr s5(env, a5);
    return (jint) ttp_session_begin_field(s0.get(), (uint32_t) a1, (int) a2, s3.get(), s4.get(), s5.get());
}

void n_ttp_session_start(JNIEnv* env, jclass, jint a0, jint a1) {
    (void) env;
    ttp_session_start((int) a0, (int) a1);
}

void n_ttp_set_steer_expo(JNIEnv* env, jclass, jdouble a0) {
    (void) env;
    ttp_set_steer_expo((double) a0);
}

jbyteArray n_ttp_showcase_inventory_json(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_showcase_inventory_json());
}

jbyteArray n_ttp_snapshot_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_snapshot_json((int) a0));
}

jint n_ttp_theme_biome_count(JNIEnv* env, jclass) {
    (void) env;
    return (jint) ttp_theme_biome_count();
}

jbyteArray n_ttp_theme_biome_for_cup(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_theme_biome_for_cup(s0.get()));
}

jbyteArray n_ttp_theme_biome_for_track(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_theme_biome_for_track(s0.get()));
}

jbyteArray n_ttp_theme_biome_name(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_theme_biome_name((int) a0));
}

jint n_ttp_theme_boost_icon(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return (jint) ttp_theme_boost_icon(s0.get());
}

jint n_ttp_theme_has_biome(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return (jint) ttp_theme_has_biome(s0.get());
}

jint n_ttp_theme_hill_color(JNIEnv* env, jclass, jbyteArray a0, jint a1) {
    CStr s0(env, a0);
    return (jint) ttp_theme_hill_color(s0.get(), (int) a1);
}

jbyteArray n_ttp_theme_prop_models(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_theme_prop_models(s0.get()));
}

jbyteArray n_ttp_theme_scenery_models(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_theme_scenery_models(s0.get()));
}

jbyteArray n_ttp_theme_showcase_models(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_theme_showcase_models());
}

jbyteArray n_ttp_theme_showcase_prop_models(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_theme_showcase_prop_models());
}

jbyteArray n_ttp_track_build_json(JNIEnv* env, jclass, jbyteArray a0, jint a1, jint a2) {
    CStr s0(env, a0);
    return toBytes(env, ttp_track_build_json(s0.get(), (int) a1, (uint32_t) a2));
}

jbyteArray n_ttp_track_frames_json(JNIEnv* env, jclass, jbyteArray a0, jbyteArray a1) {
    CStr s0(env, a0);
    CStr s1(env, a1);
    return toBytes(env, ttp_track_frames_json(s0.get(), s1.get()));
}

jbyteArray n_ttp_track_json(JNIEnv* env, jclass, jbyteArray a0, jint a1, jint a2) {
    CStr s0(env, a0);
    return toBytes(env, ttp_track_json(s0.get(), (int) a1, (uint32_t) a2));
}

jint n_ttp_track_point(JNIEnv* env, jclass, jint a0, jdouble a1, jdouble a2, jdoubleArray outArr) {
    double outv[3] = { 0 };
    const jint rc = (jint) ttp_track_point((int) a0, (double) a1, (double) a2, outv);
    if (rc && outArr && env->GetArrayLength(outArr) >= 3) env->SetDoubleArrayRegion(outArr, 0, 3, outv);
    return rc;
}

jbyteArray n_ttp_track_schematic_json(JNIEnv* env, jclass, jbyteArray a0, jint a1, jint a2) {
    CStr s0(env, a0);
    return toBytes(env, ttp_track_schematic_json(s0.get(), (int) a1, (uint32_t) a2));
}

jbyteArray n_ttp_track_supports_json(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_track_supports_json(s0.get()));
}

jbyteArray n_ttp_track_sweep_json(JNIEnv* env, jclass, jbyteArray a0, jdouble a1) {
    CStr s0(env, a0);
    return toBytes(env, ttp_track_sweep_json(s0.get(), (double) a1));
}

jbyteArray n_ttp_ui_back_effect(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_ui_back_effect(s0.get()));
}

jbyteArray n_ttp_ui_catalogue_json(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_ui_catalogue_json());
}

jint n_ttp_ui_configure(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return (jint) ttp_ui_configure(s0.get());
}

jbyteArray n_ttp_ui_cover(JNIEnv* env, jclass, jbyteArray a0, jint a1) {
    CStr s0(env, a0);
    return toBytes(env, ttp_ui_cover(s0.get(), (int) a1));
}

jint n_ttp_ui_cup_field_tint_pct(JNIEnv* env, jclass) {
    (void) env;
    return (jint) ttp_ui_cup_field_tint_pct();
}

jbyteArray n_ttp_ui_cup_slot_json(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_ui_cup_slot_json(s0.get()));
}

jint n_ttp_ui_cup_tint_rgb(JNIEnv* env, jclass, jbyteArray a0, jdouble a1) {
    CStr s0(env, a0);
    return (jint) ttp_ui_cup_tint_rgb(s0.get(), (double) a1);
}

jbyteArray n_ttp_ui_freeze_plan_json(JNIEnv* env, jclass, jint a0, jint a1, jint a2) {
    (void) env;
    return toBytes(env, ttp_ui_freeze_plan_json((int) a0, (int) a1, (int) a2));
}

jdouble n_ttp_ui_intermission_secs(JNIEnv* env, jclass, jdouble a0, jdouble a1) {
    (void) env;
    return (jdouble) ttp_ui_intermission_secs((double) a0, (double) a1);
}

jbyteArray n_ttp_ui_item_pushes_live_json(JNIEnv* env, jclass, jint a0, jbyteArray a1) {
    CStr s1(env, a1);
    return toBytes(env, ttp_ui_item_pushes_live_json((int) a0, s1.get()));
}

jint n_ttp_ui_neutral_tint_rgb(JNIEnv* env, jclass, jdouble a0) {
    (void) env;
    return (jint) ttp_ui_neutral_tint_rgb((double) a0);
}

jbyteArray n_ttp_ui_progress_json(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_ui_progress_json());
}

jint n_ttp_ui_progress_load(JNIEnv* env, jclass, jbyteArray a0, jint a1) {
    CStr s0(env, a0);
    return (jint) ttp_ui_progress_load(s0.get(), (int) a1);
}

jbyteArray n_ttp_ui_race_flow_live_json(JNIEnv* env, jclass, jint a0, jint a1) {
    (void) env;
    return toBytes(env, ttp_ui_race_flow_live_json((int) a0, (int) a1));
}

jbyteArray n_ttp_ui_reconnect_diff_json(JNIEnv* env, jclass, jbyteArray a0, jbyteArray a1) {
    CStr s0(env, a0);
    CStr s1(env, a1);
    return toBytes(env, ttp_ui_reconnect_diff_json(s0.get(), s1.get()));
}

jbyteArray n_ttp_ui_results_action_json(JNIEnv* env, jclass, jint a0) {
    (void) env;
    return toBytes(env, ttp_ui_results_action_json((int) a0));
}

jbyteArray n_ttp_ui_results_view_json(JNIEnv* env, jclass, jbyteArray a0, jdouble a1) {
    CStr s0(env, a0);
    return toBytes(env, ttp_ui_results_view_json(s0.get(), (double) a1));
}

jbyteArray n_ttp_ui_roster_seats_room_json(JNIEnv* env, jclass, jint a0, jbyteArray a1) {
    CStr s1(env, a1);
    return toBytes(env, ttp_ui_roster_seats_room_json((int) a0, s1.get()));
}

jint n_ttp_ui_screen_step(JNIEnv* env, jclass, jbyteArray a0, jbyteArray a1) {
    CStr s0(env, a0);
    CStr s1(env, a1);
    return (jint) ttp_ui_screen_step(s0.get(), s1.get());
}

jbyteArray n_ttp_ui_seat_grid_json(JNIEnv* env, jclass, jbyteArray a0) {
    CStr s0(env, a0);
    return toBytes(env, ttp_ui_seat_grid_json(s0.get()));
}

jbyteArray n_ttp_ui_series_info_live_json(JNIEnv* env, jclass, jint a0, jdouble a1) {
    (void) env;
    return toBytes(env, ttp_ui_series_info_live_json((int) a0, (double) a1));
}

jbyteArray n_ttp_ui_standings_live_json(JNIEnv* env, jclass, jint a0, jint a1, jint a2, jbyteArray a3, jdouble a4) {
    CStr s3(env, a3);
    return toBytes(env, ttp_ui_standings_live_json((int) a0, (int) a1, (int) a2, s3.get(), (double) a4));
}

jbyteArray n_ttp_ui_welcome_item_live_json(JNIEnv* env, jclass, jint a0, jbyteArray a1) {
    CStr s1(env, a1);
    return toBytes(env, ttp_ui_welcome_item_live_json((int) a0, s1.get()));
}

void n_ttp_update(JNIEnv* env, jclass, jint a0, jdouble a1) {
    (void) env;
    ttp_update((int) a0, (double) a1);
}

jbyteArray n_ttp_version(JNIEnv* env, jclass) {
    (void) env;
    return toBytes(env, ttp_version());
}

const JNINativeMethod kMethods[] = {
    { "ttp_add_bot", "(I[BDDI[B)V", (void*) n_ttp_add_bot },
    { "ttp_add_human", "(I[B[B)V", (void*) n_ttp_add_human },
    { "ttp_audio_bind", "(I)V", (void*) n_ttp_audio_bind },
    { "ttp_audio_cue_id", "(I)[B", (void*) n_ttp_audio_cue_id },
    { "ttp_audio_drain", "()Ljava/nio/ByteBuffer;", (void*) n_ttp_audio_drain },
    { "ttp_audio_frame", "(D)V", (void*) n_ttp_audio_frame },
    { "ttp_audio_music", "(I[B)V", (void*) n_ttp_audio_music },
    { "ttp_audio_roster", "(II)V", (void*) n_ttp_audio_roster },
    { "ttp_audio_song_json", "(I)[B", (void*) n_ttp_audio_song_json },
    { "ttp_audio_stop_car", "([B)V", (void*) n_ttp_audio_stop_car },
    { "ttp_audio_stop_voices", "()V", (void*) n_ttp_audio_stop_voices },
    { "ttp_blob_plan_json", "([B)[B", (void*) n_ttp_blob_plan_json },
    { "ttp_car_finished", "(I[B)I", (void*) n_ttp_car_finished },
    { "ttp_car_ids_json", "(I)[B", (void*) n_ttp_car_ids_json },
    { "ttp_car_world_pos", "(I[B[D)I", (void*) n_ttp_car_world_pos },
    { "ttp_display_antialias", "(I)V", (void*) n_ttp_display_antialias },
    { "ttp_display_asset", "([B[B)I", (void*) n_ttp_display_asset },
    { "ttp_display_bake_export", "()[B", (void*) n_ttp_display_bake_export },
    { "ttp_display_bake_import", "([B)I", (void*) n_ttp_display_bake_import },
    { "ttp_display_bake_key", "([B)[B", (void*) n_ttp_display_bake_key },
    { "ttp_display_bench", "([B)V", (void*) n_ttp_display_bench },
    { "ttp_display_bind", "(I)V", (void*) n_ttp_display_bind },
    { "ttp_display_biome", "([B)V", (void*) n_ttp_display_biome },
    { "ttp_display_build", "([B[B)I", (void*) n_ttp_display_build },
    { "ttp_display_burst", "([BDD)V", (void*) n_ttp_display_burst },
    { "ttp_display_camera", "(I)V", (void*) n_ttp_display_camera },
    { "ttp_display_cell_cards", "(I)V", (void*) n_ttp_display_cell_cards },
    { "ttp_display_cell_rects", "([FI)I", (void*) n_ttp_display_cell_rects },
    { "ttp_display_cells", "([B)V", (void*) n_ttp_display_cells },
    { "ttp_display_debug_decals", "()[B", (void*) n_ttp_display_debug_decals },
    { "ttp_display_debug_features", "(I)V", (void*) n_ttp_display_debug_features },
    { "ttp_display_debug_force_mask_layer", "(I)V", (void*) n_ttp_display_debug_force_mask_layer },
    { "ttp_display_debug_hide_cars", "(I)V", (void*) n_ttp_display_debug_hide_cars },
    { "ttp_display_debug_wipe_skids", "()V", (void*) n_ttp_display_debug_wipe_skids },
    { "ttp_display_destroy", "()V", (void*) n_ttp_display_destroy },
    { "ttp_display_dividers", "(I)V", (void*) n_ttp_display_dividers },
    { "ttp_display_drain", "()V", (void*) n_ttp_display_drain },
    { "ttp_display_fog", "(I)V", (void*) n_ttp_display_fog },
    { "ttp_display_frame", "(D)I", (void*) n_ttp_display_frame },
    { "ttp_display_gpu_ms", "()D", (void*) n_ttp_display_gpu_ms },
    { "ttp_display_hold", "(I)V", (void*) n_ttp_display_hold },
    { "ttp_display_hud", "()Ljava/nio/ByteBuffer;", (void*) n_ttp_display_hud },
    { "ttp_display_kit_field", "(I)V", (void*) n_ttp_display_kit_field },
    { "ttp_display_kit_field_layout", "()[B", (void*) n_ttp_display_kit_field_layout },
    { "ttp_display_look", "(DDDDDD)V", (void*) n_ttp_display_look },
    { "ttp_display_model_variant", "([BI)V", (void*) n_ttp_display_model_variant },
    { "ttp_display_multiview", "(I)V", (void*) n_ttp_display_multiview },
    { "ttp_display_profile", "()Ljava/nio/ByteBuffer;", (void*) n_ttp_display_profile },
    { "ttp_display_profile_names", "()[B", (void*) n_ttp_display_profile_names },
    { "ttp_display_release", "()V", (void*) n_ttp_display_release },
    { "ttp_display_reroster", "([B)I", (void*) n_ttp_display_reroster },
    { "ttp_display_resize", "(II)V", (void*) n_ttp_display_resize },
    { "ttp_display_scale_panel_ms", "()D", (void*) n_ttp_display_scale_panel_ms },
    { "ttp_display_scale_poll", "(DDDDD[D)I", (void*) n_ttp_display_scale_poll },
    { "ttp_display_scale_scene", "(D)V", (void*) n_ttp_display_scale_scene },
    { "ttp_display_shadows", "(I)V", (void*) n_ttp_display_shadows },
    { "ttp_display_showcase", "(I)V", (void*) n_ttp_display_showcase },
    { "ttp_display_slot_ids_json", "()[B", (void*) n_ttp_display_slot_ids_json },
    { "ttp_dispose", "(I)V", (void*) n_ttp_dispose },
    { "ttp_events_json", "(I)[B", (void*) n_ttp_events_json },
    { "ttp_fast_forward", "(I)V", (void*) n_ttp_fast_forward },
    { "ttp_force_finish", "(I[BD)V", (void*) n_ttp_force_finish },
    { "ttp_force_remove_car", "(I[B)I", (void*) n_ttp_force_remove_car },
    { "ttp_framing_backoff_ms", "(D)D", (void*) n_ttp_framing_backoff_ms },
    { "ttp_framing_classify", "([B)[B", (void*) n_ttp_framing_classify },
    { "ttp_framing_close_outcome", "(IDDDI)[B", (void*) n_ttp_framing_close_outcome },
    { "ttp_framing_encode_broadcast", "([B)[B", (void*) n_ttp_framing_encode_broadcast },
    { "ttp_framing_encode_close_room", "()[B", (void*) n_ttp_framing_encode_close_room },
    { "ttp_framing_encode_create", "([BD[B)[B", (void*) n_ttp_framing_encode_create },
    { "ttp_framing_encode_join", "([B[B)[B", (void*) n_ttp_framing_encode_join },
    { "ttp_framing_encode_send_to", "([B[B)[B", (void*) n_ttp_framing_encode_send_to },
    { "ttp_framing_encode_set_state", "([B)[B", (void*) n_ttp_framing_encode_set_state },
    { "ttp_framing_max_reconnect_attempts", "()D", (void*) n_ttp_framing_max_reconnect_attempts },
    { "ttp_framing_pin_url", "([B[B[B)[B", (void*) n_ttp_framing_pin_url },
    { "ttp_get_steer_expo", "()D", (void*) n_ttp_get_steer_expo },
    { "ttp_glb_ghost", "([B)[B", (void*) n_ttp_glb_ghost },
    { "ttp_glb_image_uris", "([B)[B", (void*) n_ttp_glb_image_uris },
    { "ttp_gp_advance", "(I)V", (void*) n_ttp_gp_advance },
    { "ttp_gp_apply_race", "(I[B[B[B)V", (void*) n_ttp_gp_apply_race },
    { "ttp_gp_create", "([BI)I", (void*) n_ttp_gp_create },
    { "ttp_gp_dispose", "(I)V", (void*) n_ttp_gp_dispose },
    { "ttp_gp_rekey", "(I[B[B)V", (void*) n_ttp_gp_rekey },
    { "ttp_gp_state_json", "(I)[B", (void*) n_ttp_gp_state_json },
    { "ttp_has_car", "(I[B)I", (void*) n_ttp_has_car },
    { "ttp_item_id", "(I)[B", (void*) n_ttp_item_id },
    { "ttp_last_error", "()[B", (void*) n_ttp_last_error },
    { "ttp_link_create", "()I", (void*) n_ttp_link_create },
    { "ttp_link_dispose", "(I)V", (void*) n_ttp_link_dispose },
    { "ttp_link_enqueue", "(I[BD)[B", (void*) n_ttp_link_enqueue },
    { "ttp_link_idle", "(ID)[B", (void*) n_ttp_link_idle },
    { "ttp_link_inbound", "(I[BD)[B", (void*) n_ttp_link_inbound },
    { "ttp_link_send_tick", "(ID)[B", (void*) n_ttp_link_send_tick },
    { "ttp_link_set_channel_open", "(II)V", (void*) n_ttp_link_set_channel_open },
    { "ttp_link_stats_json", "(I)[B", (void*) n_ttp_link_stats_json },
    { "ttp_net_claim_url", "([BD)[B", (void*) n_ttp_net_claim_url },
    { "ttp_net_clean_name", "([B)[B", (void*) n_ttp_net_clean_name },
    { "ttp_net_clear_pick", "(I)V", (void*) n_ttp_net_clear_pick },
    { "ttp_net_configure", "([B)I", (void*) n_ttp_net_configure },
    { "ttp_net_controller_action", "(II[B[B)[B", (void*) n_ttp_net_controller_action },
    { "ttp_net_controller_url_template", "([B[B)[B", (void*) n_ttp_net_controller_url_template },
    { "ttp_net_create_timeout_json", "(I)[B", (void*) n_ttp_net_create_timeout_json },
    { "ttp_net_effect_ops_json", "()[B", (void*) n_ttp_net_effect_ops_json },
    { "ttp_net_host_change_apply_json", "(I[B)[B", (void*) n_ttp_net_host_change_apply_json },
    { "ttp_net_init_pick", "(I[BID)V", (void*) n_ttp_net_init_pick },
    { "ttp_net_join_url", "([B[B[B[B)[B", (void*) n_ttp_net_join_url },
    { "ttp_net_liveness_json", "(IID)[B", (void*) n_ttp_net_liveness_json },
    { "ttp_net_lobby_frame", "(II[B)[B", (void*) n_ttp_net_lobby_frame },
    { "ttp_net_on_close_json", "(II)[B", (void*) n_ttp_net_on_close_json },
    { "ttp_net_on_open_json", "(I)[B", (void*) n_ttp_net_on_open_json },
    { "ttp_net_on_peer_message_json", "(II[B[BID)[B", (void*) n_ttp_net_on_peer_message_json },
    { "ttp_net_on_protocol_json", "(I[B[BD)[B", (void*) n_ttp_net_on_protocol_json },
    { "ttp_net_on_seen_json", "(I[BD)[B", (void*) n_ttp_net_on_seen_json },
    { "ttp_net_pick_json", "(I)[B", (void*) n_ttp_net_pick_json },
    { "ttp_net_reconnect_card_json", "([B[B)[B", (void*) n_ttp_net_reconnect_card_json },
    { "ttp_net_restore_room", "(I[B[B)V", (void*) n_ttp_net_restore_room },
    { "ttp_net_set_track_json", "(I[B)[B", (void*) n_ttp_net_set_track_json },
    { "ttp_net_state_change_apply_json", "(I[BD)[B", (void*) n_ttp_net_state_change_apply_json },
    { "ttp_party_version", "()[B", (void*) n_ttp_party_version },
    { "ttp_pause", "(I)V", (void*) n_ttp_pause },
    { "ttp_paused", "(I)I", (void*) n_ttp_paused },
    { "ttp_perf_pacing", "(DI)V", (void*) n_ttp_perf_pacing },
    { "ttp_perf_readout_json", "(IIID[B)[B", (void*) n_ttp_perf_readout_json },
    { "ttp_perf_reset", "()V", (void*) n_ttp_perf_reset },
    { "ttp_perf_sample", "(DDIDD)V", (void*) n_ttp_perf_sample },
    { "ttp_process_input", "(I[BIDDD)I", (void*) n_ttp_process_input },
    { "ttp_protocol_manifest_json", "()[B", (void*) n_ttp_protocol_manifest_json },
    { "ttp_race_advance_live_json", "(IIDD[B[B)[B", (void*) n_ttp_race_advance_live_json },
    { "ttp_race_auto_pause_live_json", "(III)[B", (void*) n_ttp_race_auto_pause_live_json },
    { "ttp_race_autopilot_players", "(I)V", (void*) n_ttp_race_autopilot_players },
    { "ttp_race_bench_field_json", "([BID)[B", (void*) n_ttp_race_bench_field_json },
    { "ttp_race_configure", "([B)I", (void*) n_ttp_race_configure },
    { "ttp_race_countdown_ready", "(IID)I", (void*) n_ttp_race_countdown_ready },
    { "ttp_race_demo_live_json", "(I[B[B)[B", (void*) n_ttp_race_demo_live_json },
    { "ttp_race_effect_ops_json", "()[B", (void*) n_ttp_race_effect_ops_json },
    { "ttp_race_end_party_json", "()[B", (void*) n_ttp_race_end_party_json },
    { "ttp_race_events_live_json", "(II[BIIDDD)[B", (void*) n_ttp_race_events_live_json },
    { "ttp_race_forfeit_live_json", "(I[B)[B", (void*) n_ttp_race_forfeit_live_json },
    { "ttp_race_intermission_ms", "()D", (void*) n_ttp_race_intermission_ms },
    { "ttp_race_pause_live_json", "(IIIII)[B", (void*) n_ttp_race_pause_live_json },
    { "ttp_race_personas_json", "()[B", (void*) n_ttp_race_personas_json },
    { "ttp_race_rekey_live_json", "(II[B[B)[B", (void*) n_ttp_race_rekey_live_json },
    { "ttp_race_results_failsafe_ms", "()D", (void*) n_ttp_race_results_failsafe_ms },
    { "ttp_race_resume_live_json", "(IIIII)[B", (void*) n_ttp_race_resume_live_json },
    { "ttp_race_return_live_json", "(I)[B", (void*) n_ttp_race_return_live_json },
    { "ttp_race_series_state_json", "(I)[B", (void*) n_ttp_race_series_state_json },
    { "ttp_race_start_live_json", "(IIDD[B[B)[B", (void*) n_ttp_race_start_live_json },
    { "ttp_racing", "(I)I", (void*) n_ttp_racing },
    { "ttp_rekey_car", "(I[B[B)I", (void*) n_ttp_rekey_car },
    { "ttp_results_json", "(I)[B", (void*) n_ttp_results_json },
    { "ttp_resume", "(I)V", (void*) n_ttp_resume },
    { "ttp_room_add_player", "(I[B[B)[B", (void*) n_ttp_room_add_player },
    { "ttp_room_create", "([B)I", (void*) n_ttp_room_create },
    { "ttp_room_dispose", "(I)V", (void*) n_ttp_room_dispose },
    { "ttp_room_events_json", "(I)[B", (void*) n_ttp_room_events_json },
    { "ttp_room_host_json", "(I)[B", (void*) n_ttp_room_host_json },
    { "ttp_room_list_json", "(I)[B", (void*) n_ttp_room_list_json },
    { "ttp_room_set_field", "(I[B[B[B)I", (void*) n_ttp_room_set_field },
    { "ttp_room_set_liveness_enabled", "(II)V", (void*) n_ttp_room_set_liveness_enabled },
    { "ttp_room_set_master", "(I[B)V", (void*) n_ttp_room_set_master },
    { "ttp_room_state", "(I)[B", (void*) n_ttp_room_state },
    { "ttp_room_transition_to", "(I[B)I", (void*) n_ttp_room_transition_to },
    { "ttp_schematic_pack", "([BD)[B", (void*) n_ttp_schematic_pack },
    { "ttp_schematic_points_json", "([B)[B", (void*) n_ttp_schematic_points_json },
    { "ttp_schematic_view_size", "()I", (void*) n_ttp_schematic_view_size },
    { "ttp_session_begin", "([BII[B)I", (void*) n_ttp_session_begin },
    { "ttp_session_begin_field", "([BII[B[B[B)I", (void*) n_ttp_session_begin_field },
    { "ttp_session_start", "(II)V", (void*) n_ttp_session_start },
    { "ttp_set_steer_expo", "(D)V", (void*) n_ttp_set_steer_expo },
    { "ttp_showcase_inventory_json", "()[B", (void*) n_ttp_showcase_inventory_json },
    { "ttp_snapshot_json", "(I)[B", (void*) n_ttp_snapshot_json },
    { "ttp_theme_biome_count", "()I", (void*) n_ttp_theme_biome_count },
    { "ttp_theme_biome_for_cup", "([B)[B", (void*) n_ttp_theme_biome_for_cup },
    { "ttp_theme_biome_for_track", "([B)[B", (void*) n_ttp_theme_biome_for_track },
    { "ttp_theme_biome_name", "(I)[B", (void*) n_ttp_theme_biome_name },
    { "ttp_theme_boost_icon", "([B)I", (void*) n_ttp_theme_boost_icon },
    { "ttp_theme_has_biome", "([B)I", (void*) n_ttp_theme_has_biome },
    { "ttp_theme_hill_color", "([BI)I", (void*) n_ttp_theme_hill_color },
    { "ttp_theme_prop_models", "([B)[B", (void*) n_ttp_theme_prop_models },
    { "ttp_theme_scenery_models", "([B)[B", (void*) n_ttp_theme_scenery_models },
    { "ttp_theme_showcase_models", "()[B", (void*) n_ttp_theme_showcase_models },
    { "ttp_theme_showcase_prop_models", "()[B", (void*) n_ttp_theme_showcase_prop_models },
    { "ttp_track_build_json", "([BII)[B", (void*) n_ttp_track_build_json },
    { "ttp_track_frames_json", "([B[B)[B", (void*) n_ttp_track_frames_json },
    { "ttp_track_json", "([BII)[B", (void*) n_ttp_track_json },
    { "ttp_track_point", "(IDD[D)I", (void*) n_ttp_track_point },
    { "ttp_track_schematic_json", "([BII)[B", (void*) n_ttp_track_schematic_json },
    { "ttp_track_supports_json", "([B)[B", (void*) n_ttp_track_supports_json },
    { "ttp_track_sweep_json", "([BD)[B", (void*) n_ttp_track_sweep_json },
    { "ttp_ui_back_effect", "([B)[B", (void*) n_ttp_ui_back_effect },
    { "ttp_ui_catalogue_json", "()[B", (void*) n_ttp_ui_catalogue_json },
    { "ttp_ui_configure", "([B)I", (void*) n_ttp_ui_configure },
    { "ttp_ui_cover", "([BI)[B", (void*) n_ttp_ui_cover },
    { "ttp_ui_cup_field_tint_pct", "()I", (void*) n_ttp_ui_cup_field_tint_pct },
    { "ttp_ui_cup_slot_json", "([B)[B", (void*) n_ttp_ui_cup_slot_json },
    { "ttp_ui_cup_tint_rgb", "([BD)I", (void*) n_ttp_ui_cup_tint_rgb },
    { "ttp_ui_freeze_plan_json", "(III)[B", (void*) n_ttp_ui_freeze_plan_json },
    { "ttp_ui_intermission_secs", "(DD)D", (void*) n_ttp_ui_intermission_secs },
    { "ttp_ui_item_pushes_live_json", "(I[B)[B", (void*) n_ttp_ui_item_pushes_live_json },
    { "ttp_ui_neutral_tint_rgb", "(D)I", (void*) n_ttp_ui_neutral_tint_rgb },
    { "ttp_ui_progress_json", "()[B", (void*) n_ttp_ui_progress_json },
    { "ttp_ui_progress_load", "([BI)I", (void*) n_ttp_ui_progress_load },
    { "ttp_ui_race_flow_live_json", "(II)[B", (void*) n_ttp_ui_race_flow_live_json },
    { "ttp_ui_reconnect_diff_json", "([B[B)[B", (void*) n_ttp_ui_reconnect_diff_json },
    { "ttp_ui_results_action_json", "(I)[B", (void*) n_ttp_ui_results_action_json },
    { "ttp_ui_results_view_json", "([BD)[B", (void*) n_ttp_ui_results_view_json },
    { "ttp_ui_roster_seats_room_json", "(I[B)[B", (void*) n_ttp_ui_roster_seats_room_json },
    { "ttp_ui_screen_step", "([B[B)I", (void*) n_ttp_ui_screen_step },
    { "ttp_ui_seat_grid_json", "([B)[B", (void*) n_ttp_ui_seat_grid_json },
    { "ttp_ui_series_info_live_json", "(ID)[B", (void*) n_ttp_ui_series_info_live_json },
    { "ttp_ui_standings_live_json", "(III[BD)[B", (void*) n_ttp_ui_standings_live_json },
    { "ttp_ui_welcome_item_live_json", "(I[B)[B", (void*) n_ttp_ui_welcome_item_live_json },
    { "ttp_update", "(ID)V", (void*) n_ttp_update },
    { "ttp_version", "()[B", (void*) n_ttp_version },
};

}  // namespace

// Registered in one table at load. A name or signature that does not match
// the Kotlin object fails HERE — before an Activity exists, with the
// offending method named by the VM — rather than as an UnsatisfiedLinkError
// at whatever moment of a party first reaches it.
extern "C" JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
    JNIEnv* env = nullptr;
    if (vm->GetEnv((void**) &env, JNI_VERSION_1_6) != JNI_OK) return JNI_ERR;
    jclass cls = env->FindClass("games/couchpad/tinytrack/Ttp");
    if (!cls) return JNI_ERR;
    const int n = (int) (sizeof(kMethods) / sizeof(kMethods[0]));
    if (env->RegisterNatives(cls, kMethods, n) != JNI_OK) return JNI_ERR;
    return JNI_VERSION_1_6;
}
