// GENERATED by scripts/gen-jni.mjs — do not edit.
//
// The Kotlin half of the bridge; native/runtime/ttp_jni.cc is the other,
// emitted from the same parse in the same run.
//
// EVERY STRING IS A ByteArray, decoded UTF-8 by TtpJson — never a String
// across the boundary. See the C file's header for why jstring is wrong.
//
// The C spellings are kept against Kotlin convention so that one grep for
// ttp_display_build finds the header, the tvOS Swift call site, the web's
// Stage.js and this declaration together.
package games.couchpad.tinytrack

import java.nio.ByteBuffer

@Suppress("FunctionName", "unused")
object Ttp {
    /** Registers all 222 natives via JNI_OnLoad; a mismatch fails here. */
    fun load() { System.loadLibrary("ttp_runtime_android") }

    external fun ttp_add_bot(h: Int, idJson: ByteArray?, caution: Double, laneBias: Double, aiSeed: Int, statsJsonOrNull: ByteArray?)
    external fun ttp_add_human(h: Int, idJson: ByteArray?, statsJsonOrNull: ByteArray?)
    external fun ttp_audio_bind(session: Int)
    external fun ttp_audio_cue_id(code: Int): ByteArray?
    external fun ttp_audio_drain(): ByteBuffer?
    external fun ttp_audio_frame(nowMs: Double)
    external fun ttp_audio_music(op: Int, biomeOrNull: ByteArray?)
    external fun ttp_audio_roster(count: Int, inLobby: Int)
    external fun ttp_audio_song_json(index: Int): ByteArray?
    external fun ttp_audio_stop_car(idJson: ByteArray?)
    external fun ttp_audio_stop_voices()
    external fun ttp_car_finished(h: Int, idJson: ByteArray?): Int
    external fun ttp_car_ids_json(h: Int): ByteArray?
    external fun ttp_car_world_pos(h: Int, idJson: ByteArray?, out3: DoubleArray): Int
    external fun ttp_display_antialias(on: Int)
    external fun ttp_display_asset(name: ByteArray?, bytes: ByteArray?): Int
    external fun ttp_display_asset_plan(wantJson: ByteArray?): ByteArray?
    external fun ttp_display_asset_textures(): ByteArray?
    external fun ttp_display_bench(model: ByteArray?)
    external fun ttp_display_bind(session: Int)
    external fun ttp_display_biome(name: ByteArray?)
    external fun ttp_display_blob_export(store: ByteArray?, name: ByteArray?): ByteArray?
    external fun ttp_display_blob_keep(store: ByteArray?): ByteArray?
    external fun ttp_display_blob_offer(store: ByteArray?, bytes: ByteArray?)
    external fun ttp_display_blob_plan(store: ByteArray?, trackId: ByteArray?, generation: ByteArray?, entriesJson: ByteArray?): ByteArray?
    external fun ttp_display_blob_ready(): Int
    external fun ttp_display_blob_stores(): ByteArray?
    external fun ttp_display_blob_wrote(store: ByteArray?, name: ByteArray?)
    external fun ttp_display_build(trackId: ByteArray?, rosterJson: ByteArray?): Int
    external fun ttp_display_burst(idJson: ByteArray?, s: Double, lat: Double)
    external fun ttp_display_camera(mode: Int)
    external fun ttp_display_cell_cards(mask: Int)
    external fun ttp_display_cell_rects(out: FloatArray, maxCells: Int): Int
    external fun ttp_display_cells(idsJson: ByteArray?)
    // ttp_display_create: not bound — see OVERRIDES in scripts/gen-jni.mjs.
    external fun ttp_display_debug_decals(): ByteArray?
    external fun ttp_display_debug_features(mask: Int)
    external fun ttp_display_debug_force_mask_layer(layer: Int)
    external fun ttp_display_debug_hide_cars(on: Int)
    external fun ttp_display_debug_wipe_skids()
    external fun ttp_display_destroy()
    external fun ttp_display_dividers(enabled: Int)
    external fun ttp_display_drain()
    external fun ttp_display_dress_keep(frac: Float)
    external fun ttp_display_dress_sheets(on: Int)
    external fun ttp_display_fog(enabled: Int)
    external fun ttp_display_frame(dtSeconds: Double): Int
    external fun ttp_display_gpu_ms(): Double
    external fun ttp_display_hold(held: Int)
    external fun ttp_display_hud(): ByteBuffer?
    external fun ttp_display_kit_field(count: Int)
    external fun ttp_display_kit_field_layout(): ByteArray?
    external fun ttp_display_look(eyeX: Double, eyeY: Double, eyeZ: Double, tgtX: Double, tgtY: Double, tgtZ: Double)
    external fun ttp_display_model_variant(model: ByteArray?, variant: Int)
    external fun ttp_display_multiview(mode: Int)
    external fun ttp_display_profile(): ByteBuffer?
    external fun ttp_display_profile_names(): ByteArray?
    external fun ttp_display_release()
    external fun ttp_display_reroster(rosterJson: ByteArray?): Int
    external fun ttp_display_resize(width: Int, height: Int)
    external fun ttp_display_safe_insets(fx: Float, fy: Float)
    external fun ttp_display_scale_panel_ms(): Double
    external fun ttp_display_scale_poll(tMs: Double, minScale: Double, maxScale: Double, baseLines: Double, panelMs: Double, out2: DoubleArray): Int
    external fun ttp_display_scale_scene(tMs: Double)
    external fun ttp_display_settled(): Int
    external fun ttp_display_shadows(enabled: Int)
    external fun ttp_display_showcase(on: Int)
    external fun ttp_display_slot_ids_json(): ByteArray?
    external fun ttp_dispose(h: Int)
    external fun ttp_events_json(h: Int): ByteArray?
    external fun ttp_fast_forward(h: Int)
    external fun ttp_force_finish(h: Int, idJson: ByteArray?, time: Double)
    external fun ttp_force_remove_car(h: Int, idJson: ByteArray?): Int
    external fun ttp_framing_backoff_ms(attempt: Double): Double
    external fun ttp_framing_classify(frameText: ByteArray?): ByteArray?
    external fun ttp_framing_close_outcome(hasCode: Int, code: Double, attemptBefore: Double, maxAttempts: Double, shouldReconnectBefore: Int): ByteArray?
    external fun ttp_framing_encode_broadcast(dataJson: ByteArray?): ByteArray?
    external fun ttp_framing_encode_close_room(): ByteArray?
    external fun ttp_framing_encode_create(clientId: ByteArray?, maxClients: Double, urlOrNull: ByteArray?): ByteArray?
    external fun ttp_framing_encode_join(clientId: ByteArray?, room: ByteArray?): ByteArray?
    external fun ttp_framing_encode_send_to(toJson: ByteArray?, dataJson: ByteArray?): ByteArray?
    external fun ttp_framing_encode_set_state(dataJson: ByteArray?): ByteArray?
    external fun ttp_framing_max_reconnect_attempts(): Double
    external fun ttp_framing_pin_url(base: ByteArray?, room: ByteArray?, instance: ByteArray?): ByteArray?
    external fun ttp_get_steer_expo(): Double
    external fun ttp_glb_ghost(bytes: ByteArray?): ByteArray?
    external fun ttp_glb_image_uris(bytes: ByteArray?): ByteArray?
    external fun ttp_gp_advance(h: Int)
    external fun ttp_gp_apply_race(h: Int, resultsJson: ByteArray?, fieldJson: ByteArray?, drawnTrackIdOrNull: ByteArray?)
    external fun ttp_gp_create(cupJson: ByteArray?, endless: Int): Int
    external fun ttp_gp_dispose(h: Int)
    external fun ttp_gp_rekey(h: Int, oldIdJson: ByteArray?, newIdJson: ByteArray?)
    external fun ttp_gp_state_json(h: Int): ByteArray?
    external fun ttp_has_car(h: Int, idJson: ByteArray?): Int
    external fun ttp_item_id(code: Int): ByteArray?
    external fun ttp_last_error(): ByteArray?
    external fun ttp_link_create(): Int
    external fun ttp_link_dispose(h: Int)
    external fun ttp_link_enqueue(h: Int, evJson: ByteArray?, nowMs: Double): ByteArray?
    external fun ttp_link_idle(h: Int, nowMs: Double): ByteArray?
    external fun ttp_link_inbound(h: Int, packetText: ByteArray?, nowMs: Double): ByteArray?
    external fun ttp_link_send_tick(h: Int, nowMs: Double): ByteArray?
    external fun ttp_link_set_channel_open(h: Int, open: Int)
    external fun ttp_link_stats_json(h: Int): ByteArray?
    external fun ttp_net_claim_url(url: ByteArray?, peerIndex: Double): ByteArray?
    external fun ttp_net_clean_name(valueJson: ByteArray?): ByteArray?
    external fun ttp_net_clear_pick(roomHandle: Int)
    external fun ttp_net_configure(chooserJson: ByteArray?): Int
    external fun ttp_net_controller_action(roomHandle: Int, sessionHandle: Int, fromJson: ByteArray?, type: ByteArray?): ByteArray?
    external fun ttp_net_controller_url_template(base: ByteArray?, platform: ByteArray?): ByteArray?
    external fun ttp_net_create_timeout_json(roomHandle: Int): ByteArray?
    external fun ttp_net_effect_ops_json(): ByteArray?
    external fun ttp_net_host_change_apply_json(roomHandle: Int, hostPeerIdJson: ByteArray?): ByteArray?
    external fun ttp_net_init_pick(roomHandle: Int, defaultTrackIdOrNull: ByteArray?, hasBag: Int, bagSeed: Double)
    external fun ttp_net_join_url(base: ByteArray?, room: ByteArray?, instance: ByteArray?, platform: ByteArray?): ByteArray?
    external fun ttp_net_liveness_json(roomHandle: Int, sessionHandle: Int, nowMs: Double): ByteArray?
    external fun ttp_net_lobby_frame(roomHandle: Int, sessionHandle: Int, fieldsJson: ByteArray?): ByteArray?
    external fun ttp_net_on_close_json(roomHandle: Int, roomClosed: Int): ByteArray?
    external fun ttp_net_on_open_json(roomHandle: Int): ByteArray?
    external fun ttp_net_on_peer_message_json(roomHandle: Int, sessionHandle: Int, fromJson: ByteArray?, msgJson: ByteArray?, isSignal: Int, nowMs: Double): ByteArray?
    external fun ttp_net_on_protocol_json(roomHandle: Int, type: ByteArray?, msgJson: ByteArray?, nowMs: Double): ByteArray?
    external fun ttp_net_on_seen_json(roomHandle: Int, peerIdJson: ByteArray?, nowMs: Double): ByteArray?
    external fun ttp_net_pick_json(roomHandle: Int): ByteArray?
    external fun ttp_net_reconnect_card_json(seatJson: ByteArray?, url: ByteArray?): ByteArray?
    external fun ttp_net_restore_room(roomHandle: Int, code: ByteArray?, instance: ByteArray?)
    external fun ttp_net_set_track_json(roomHandle: Int, trackId: ByteArray?): ByteArray?
    external fun ttp_net_state_change_apply_json(roomHandle: Int, to: ByteArray?, nowMs: Double): ByteArray?
    external fun ttp_party_version(): ByteArray?
    external fun ttp_pause(h: Int)
    external fun ttp_paused(h: Int): Int
    external fun ttp_perf_pacing(panelMs: Double, divisor: Int)
    external fun ttp_perf_readout_json(cells: Int, width: Int, height: Int, dpr: Double, trackOrNull: ByteArray?): ByteArray?
    external fun ttp_perf_reset()
    external fun ttp_perf_sample(tMs: Double, intervalMs: Double, presented: Int, cpuMs: Double, gpuMs: Double)
    external fun ttp_process_input(h: Int, idJson: ByteArray?, mask: Int, s: Double, b: Double, u: Double): Int
    external fun ttp_protocol_manifest_json(): ByteArray?
    external fun ttp_race_advance_live_json(roomHandle: Int, sceneReady: Int, seed: Double, countdownSeconds: Double, forceItemOrNull: ByteArray?, botCapJson: ByteArray?): ByteArray?
    external fun ttp_race_auto_pause_live_json(sessionHandle: Int, roomHandle: Int, raceEnded: Int): ByteArray?
    external fun ttp_race_autopilot_players(on: Int)
    external fun ttp_race_bench_field_json(trackId: ByteArray?, players: Int, seed: Double): ByteArray?
    external fun ttp_race_configure(json: ByteArray?): Int
    external fun ttp_race_countdown_ready(sceneBuilt: Int, measuring: Int, sinceLaunchMs: Double): Int
    external fun ttp_race_demo_live_json(roomHandle: Int, trackId: ByteArray?, botCapJson: ByteArray?): ByteArray?
    external fun ttp_race_effect_ops_json(): ByteArray?
    external fun ttp_race_end_party_json(): ByteArray?
    external fun ttp_race_events_live_json(sessionHandle: Int, roomHandle: Int, biome: ByteArray?, audioReady: Int, fastForwarding: Int, intermissionMs: Double, nowMs: Double, resultsFailsafeMs: Double): ByteArray?
    external fun ttp_race_forfeit_live_json(sessionHandle: Int, peerIdJson: ByteArray?): ByteArray?
    external fun ttp_race_intermission_ms(): Double
    external fun ttp_race_pause_live_json(sessionHandle: Int, roomHandle: Int, paused: Int, autoPaused: Int, raceEnded: Int): ByteArray?
    external fun ttp_race_personas_json(): ByteArray?
    external fun ttp_race_rekey_live_json(sessionHandle: Int, roomHandle: Int, oldIdJson: ByteArray?, newIdJson: ByteArray?): ByteArray?
    external fun ttp_race_results_failsafe_ms(): Double
    external fun ttp_race_resume_live_json(sessionHandle: Int, roomHandle: Int, paused: Int, autoPaused: Int, raceEnded: Int): ByteArray?
    external fun ttp_race_return_live_json(roomHandle: Int): ByteArray?
    external fun ttp_race_series_state_json(roomHandle: Int): ByteArray?
    external fun ttp_race_start_live_json(roomHandle: Int, sceneReady: Int, seed: Double, countdownSeconds: Double, forceItemOrNull: ByteArray?, botCapJson: ByteArray?): ByteArray?
    external fun ttp_racing(h: Int): Int
    external fun ttp_rekey_car(h: Int, oldJson: ByteArray?, newJson: ByteArray?): Int
    external fun ttp_results_json(h: Int): ByteArray?
    external fun ttp_resume(h: Int)
    external fun ttp_room_add_player(h: Int, peerIdJson: ByteArray?, fieldsJsonOrNull: ByteArray?): ByteArray?
    external fun ttp_room_create(configJson: ByteArray?): Int
    external fun ttp_room_dispose(h: Int)
    external fun ttp_room_events_json(h: Int): ByteArray?
    external fun ttp_room_host_json(h: Int): ByteArray?
    external fun ttp_room_list_json(h: Int): ByteArray?
    external fun ttp_room_set_field(h: Int, peerIdJson: ByteArray?, key: ByteArray?, valueJson: ByteArray?): Int
    external fun ttp_room_set_liveness_enabled(h: Int, enabled: Int)
    external fun ttp_room_set_master(h: Int, peerIdJson: ByteArray?)
    external fun ttp_room_state(h: Int): ByteArray?
    external fun ttp_room_transition_to(h: Int, stateName: ByteArray?): Int
    external fun ttp_schematic_pack(pathD: ByteArray?, eps: Double): ByteArray?
    external fun ttp_schematic_points_json(pathD: ByteArray?): ByteArray?
    external fun ttp_schematic_view_size(): Int
    external fun ttp_session_begin(trackId: ByteArray?, seed: Int, laps: Int, forceItemOrNull: ByteArray?): Int
    external fun ttp_session_begin_field(trackId: ByteArray?, seed: Int, laps: Int, forceItemOrNull: ByteArray?, fieldJson: ByteArray?, botsJson: ByteArray?): Int
    external fun ttp_session_start(h: Int, countdownSeconds: Int)
    external fun ttp_set_steer_expo(v: Double)
    external fun ttp_showcase_inventory_json(): ByteArray?
    external fun ttp_snapshot_json(h: Int): ByteArray?
    external fun ttp_theme_biome_count(): Int
    external fun ttp_theme_biome_for_cup(cupId: ByteArray?): ByteArray?
    external fun ttp_theme_biome_for_track(trackId: ByteArray?): ByteArray?
    external fun ttp_theme_biome_name(index: Int): ByteArray?
    external fun ttp_theme_boost_icon(biomeName: ByteArray?): Int
    external fun ttp_theme_has_biome(name: ByteArray?): Int
    external fun ttp_theme_hill_color(biomeName: ByteArray?, index: Int): Int
    external fun ttp_theme_prop_models(biomeName: ByteArray?): ByteArray?
    external fun ttp_theme_scenery_models(biomeName: ByteArray?): ByteArray?
    external fun ttp_theme_showcase_models(): ByteArray?
    external fun ttp_theme_showcase_prop_models(): ByteArray?
    external fun ttp_track_build_json(descriptorJson: ByteArray?, laps: Int, seed: Int): ByteArray?
    external fun ttp_track_frames_json(trackIdOrDescriptor: ByteArray?, sListJson: ByteArray?): ByteArray?
    external fun ttp_track_json(trackId: ByteArray?, laps: Int, seed: Int): ByteArray?
    external fun ttp_track_point(h: Int, s: Double, lat: Double, out3: DoubleArray): Int
    external fun ttp_track_schematic_json(trackId: ByteArray?, laps: Int, seed: Int): ByteArray?
    external fun ttp_track_supports_json(trackIdOrDescriptor: ByteArray?): ByteArray?
    external fun ttp_track_sweep_json(trackIdOrDescriptor: ByteArray?, step: Double): ByteArray?
    external fun ttp_ui_back_effect(screen: ByteArray?, paused: Int, raceEnded: Int): ByteArray?
    external fun ttp_ui_catalogue_json(): ByteArray?
    external fun ttp_ui_configure(json: ByteArray?): Int
    external fun ttp_ui_cover(screen: ByteArray?, scenePainted: Int): ByteArray?
    external fun ttp_ui_cup_field_tint_pct(): Int
    external fun ttp_ui_cup_slot_json(pickJson: ByteArray?): ByteArray?
    external fun ttp_ui_cup_tint_rgb(cupIdOrNull: ByteArray?, pct: Double): Int
    external fun ttp_ui_freeze_plan_json(paused: Int, autoPaused: Int, sessionPaused: Int): ByteArray?
    external fun ttp_ui_intermission_secs(deadlineMs: Double, nowMs: Double): Double
    external fun ttp_ui_item_pushes_live_json(sessionHandle: Int, lastItemJson: ByteArray?): ByteArray?
    external fun ttp_ui_neutral_tint_rgb(pct: Double): Int
    external fun ttp_ui_progress_json(): ByteArray?
    external fun ttp_ui_progress_load(jsonOrNull: ByteArray?, unlockAll: Int): Int
    external fun ttp_ui_race_flow_live_json(sessionHandle: Int, roomHandle: Int): ByteArray?
    external fun ttp_ui_reconnect_diff_json(shownIdsJson: ByteArray?, seatIdsJson: ByteArray?): ByteArray?
    external fun ttp_ui_results_action_json(roomHandle: Int): ByteArray?
    external fun ttp_ui_results_view_json(boardJson: ByteArray?, intermissionMs: Double): ByteArray?
    external fun ttp_ui_roster_seats_room_json(roomHandle: Int, hostIdJson: ByteArray?): ByteArray?
    external fun ttp_ui_screen_step(prevScreen: ByteArray?, nextScreen: ByteArray?): Int
    external fun ttp_ui_seat_grid_json(seatsJson: ByteArray?): ByteArray?
    external fun ttp_ui_series_info_live_json(gpHandle: Int, autoAdvanceMs: Double): ByteArray?
    external fun ttp_ui_standings_live_json(sessionHandle: Int, roomHandle: Int, over: Int, resultsJsonOrNull: ByteArray?, autoAdvanceMs: Double): ByteArray?
    external fun ttp_ui_welcome_item_live_json(sessionHandle: Int, peerIdJson: ByteArray?): ByteArray?
    external fun ttp_update(h: Int, dtMs: Double)
    external fun ttp_version(): ByteArray?
}
