// Bake the info screen's legal data into Swift: the two couchpad.games links
// the QR cards encode, and the attribution list the Licenses board renders.
//
//   node shells/tvos/scripts/gen-legal.mjs      (called by stage-assets.sh)
//
// SINGLE-SOURCED, like gen-scenarios.mjs beside it. The list itself is built by
// `scripts/shell-credits.mjs` out of `public/shared/credits.js` + the live music
// catalogue — the same two modules the web's /licenses.html page renders — and
// the privacy/imprint URLs are read out of the display's own legal footer.
// Nothing here is a second copy of a fact the web tree states.
//
// WHAT IS DECIDED HERE, and may not be anywhere else: the .ipa does not ship
// what the browser ships. The shared module drops the two web-only credits; the
// two packages that are this bundle's ALONE are below, and that half of the
// DELTA is the only thing this file adds. `tests/tvos-legal.test.js` fails if
// either stops matching the tree.
//
// The output is BUILD OUTPUT (Generated/ is gitignored) and stage-assets.sh
// reruns it on every staging, so the Swift can never be staler than the last
// stage. The notice texts it names are staged next to it, into
// Generated/assets/licenses/.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import * as shared from '../../../scripts/shell-credits.mjs';
import { ROOT } from '../../../scripts/shell-credits.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '..', 'Generated', 'Legal.swift');

// Re-exported so the gate reads one module: what a browser ships and this does
// not, and where a shared notice comes from, are both the shared module's.
export const { WEB_ONLY, SHARED_NOTICES, legalLinks } = shared;

// The .ipa's own third-party code, which no web page credits because the
// browser provides both: WebRTC (tvOS ships none, and the fastlane needs one)
// and the SVG rasterizer for the shared item icons. `notice` names a file under
// TinyTrackParty/Resources/Licenses — see the SOURCES.md there for provenance.
export const TVOS_ONLY = [
  {
    section: 'Software',
    title: 'LiveKit WebRTC (the input fastlane)',
    author: 'The WebRTC project authors',
    license: 'BSD-3-Clause',
    url: 'https://github.com/livekit/webrtc-xcframework',
    notice: 'LiveKitWebRTC-LICENSE.txt',
  },
  {
    section: 'Software',
    title: 'SwiftDraw (draws the item icons)',
    author: 'Simon Whitty',
    license: 'zlib',
    // zlib is the one license only this bundle uses, so it is the one id the
    // shared table cannot answer for; anything else has to be added to
    // credits.js LICENSES where the web can see it too.
    licenseURL: 'https://zlib.net/zlib_license.html',
    url: 'https://github.com/swhitty/SwiftDraw',
    notice: 'SwiftDraw-LICENSE.txt',
  },
];

export const TVOS_NOTICES = Object.fromEntries(
  TVOS_ONLY.filter((e) => e.notice)
    .map((e) => [e.notice, `shells/tvos/TinyTrackParty/Resources/Licenses/${e.notice}`]));

/// Where each of those two texts was copied FROM, inside SwiftPM's checkout of
/// the pinned version (paths relative to a `SourcePackages` directory). Machine
/// readable so `tests/tvos-legal.test.js` can diff the committed copy against
/// the package that is actually resolved, and catch the one drift SOURCES.md can
/// only ask for in prose: a version bump whose license text moved.
///
/// SwiftPM checks packages out under DerivedData, so this check can only run on
/// a machine that has built the app — it skips where it cannot look, which is
/// why it is a safety net and not the obligation itself.
export const TVOS_NOTICE_UPSTREAM = {
  'SwiftDraw-LICENSE.txt': 'checkouts/SwiftDraw/LICENSE.txt',
  'LiveKitWebRTC-LICENSE.txt':
    'artifacts/webrtc-xcframework/LiveKitWebRTC/LiveKitWebRTC.xcframework/LICENSE',
};

/// The list the Licenses board renders.
export const entries = () => shared.entries(TVOS_ONLY);

/// Every file that list's rows open, as bundle-name -> source path in the tree.
/// stage-assets.sh copies exactly this set into Generated/assets/licenses.
export const texts = () => shared.texts(entries(), TVOS_NOTICES);

const swiftString = (s) => `"${String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;

function source() {
  const links = legalLinks();
  const rows = entries().map((e) => '        .init(section: ' + swiftString(e.section)
    + ', title: ' + swiftString(e.title)
    + ', author: ' + swiftString(e.author)
    + ', license: ' + swiftString(e.license)
    + ', licenseURL: ' + swiftString(e.licenseURL)
    + ', url: ' + swiftString(e.url)
    + ', text: ' + swiftString(e.text) + ')').join(',\n');

  return `// GENERATED by shells/tvos/scripts/gen-legal.mjs — do not edit.
//
// The info screen's legal data: the couchpad.games pages the QR cards encode
// (read from the web display's own legal footer) and the attribution list, from
// public/shared/credits.js + the live music catalogue, adjusted for what this
// bundle actually contains. See the generator's header for that delta.

enum Legal {

    /// The two central legal pages. They are couchpad.games's, not this game's,
    /// and a TV cannot open either — which is why the info board shows them as
    /// QR codes for the phone the player is already holding.
    static let privacyURL = ${swiftString(links.privacy)}
    static let imprintURL = ${swiftString(links.imprint)}

    /// One credited work. \`text\` is what its row opens, as a file name under
    /// \`assets/licenses\` in the bundle: the notice this build SHIPS for the work
    /// where its license demands one travel, else the text of the license itself.
    /// EVERY row has one — a television cannot follow the link a browser gets.
    struct Entry: Identifiable, Hashable {
        let section: String
        let title: String
        let author: String
        let license: String
        let licenseURL: String
        let url: String
        let text: String

        var id: String { section + "/" + title }
    }

    static let entries: [Entry] = [
${rows}
    ]
}
`;
}

// Importable (tests/tvos-legal.test.js reads the same data) and runnable.
//
// It copies the texts itself rather than leaving a list for stage-assets.sh to
// repeat: the set is exactly what `texts()` derives from the entries, so a
// credit that gains or loses a notice cannot leave the bundle carrying the
// wrong files.
// `pathToFileURL` rather than a `file://` template: a URL percent-encodes, so a
// checkout under a path with a space (or any non-ASCII) never matches the
// hand-built string — and the failure is that this writes NOTHING, leaving the
// last stage's Legal.swift in place. This tree is worked in many worktrees at
// once, so their names are not something to bet on.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, source());

  const dest = path.join(HERE, '..', 'Generated', 'assets', 'licenses');
  fs.rmSync(dest, { recursive: true, force: true });
  fs.mkdirSync(dest, { recursive: true });
  const staged = texts();
  for (const [name, src] of Object.entries(staged)) {
    fs.copyFileSync(path.join(ROOT, src), path.join(dest, name));
  }
  console.log(`==> ${entries().length} credits, ${Object.keys(staged).length} texts`
    + ' -> Generated/Legal.swift + assets/licenses');
}
