#!/usr/bin/env bash
# Make shells/tvos/ ready to hand to xcodebuild, for one SDK slice.
#
#   prepare.sh [device|simulator]     (default: device)
#
# WHY THIS EXISTS. The four steps below have a required order, and until this
# script the order lived only in prose — build-runtime-tvos.sh's closing line
# told you what to run next and stage-assets.sh checked that the materials
# EXISTED but never that they were current. Every way of getting it wrong is
# silent:
#
#   - skip the runtime build and the app links the previous libttp_runtime_tvos.a.
#     Measured: editing a file under native/ and rebuilding the app leaves the
#     archive byte-identical and exits 0. The web leg cannot do this — the
#     artifact is stamped and tests/native-artifact.test.js fails — but no ctest
#     compiles the tvOS surface and nothing stamped the .a, so the television
#     showed an engine that was not the code in the tree.
#   - skip staging and the bundle keeps the previous .filamat / cues / tokens.
#     The shell names stage-assets.sh in assertion messages across most of its
#     asset-reading files, which is a fair measure of how often this one landed.
#   - skip xcodegen and an edited project.yml is ignored, so the build is made
#     from a stale project with no error anywhere.
#
# None of that is worth a freshness CHECK of the kind the web leg needs, because
# every step here is already incremental: ninja no-ops the runtime build, the
# staged bundle is a few MB of copy, and xcodegen rewrites one project. Doing all
# four unconditionally measures well under a second on a warm tree — cheaper than
# the machinery that would detect one being skipped, and it removes the failure
# mode instead of reporting it. Time it yourself before trading that away.
#
# It is NOT a build of the app: callers do their own xcodebuild, because they
# want different verbs (`build` for shells/tvos/scripts/build.sh, `test` for
# scripts/capture-shots-tvos.mjs) and different signing.
set -euo pipefail

WHICH="${1:-device}"
case "$WHICH" in
  device|simulator) ;;
  *) echo "usage: prepare.sh [device|simulator]" >&2; exit 2 ;;
esac

HERE="$(cd "$(dirname "$0")" && pwd)"
TVOS="$(cd "$HERE/.." && pwd)"
ROOT="$(cd "$TVOS/../.." && pwd)"

# ---- 1. the engine, for this SDK -------------------------------------------
# It owns the missing-SDK diagnosis too — it checks the same include/Engine.h the
# app's search paths resolve to, and prints the two commands that build one. So
# nothing below re-checks it: a second copy of that guard could only ever fire
# after this line had already succeeded.
"$ROOT/native/scripts/build-runtime-tvos.sh" "$WHICH"

# ---- 2. the bundle ----------------------------------------------------------
# After step 1, never before: it copies the .filamat blobs that step just
# compiled, and the other way round bundles the previous set.
"$HERE/stage-assets.sh"

# ---- 3. which Filament the APP links ----------------------------------------
# The same resolver every artifact build sources, so the app and the engine
# archive cannot name different trees. project.yml reads this file instead of
# carrying a path of its own — see the configFiles note there for the defect
# that cost.
#
# Written every run rather than only when absent: the pin moving is exactly when
# a cached copy would be wrong.
# shellcheck disable=SC1091
source "$ROOT/native/scripts/filament-checkout.sh"   # sets FILAMENT_SRC + FILAMENT_COMMIT
mkdir -p "$TVOS/Generated"
cat > "$TVOS/Generated/filament.xcconfig" <<XCCONFIG
// GENERATED by shells/tvos/scripts/prepare.sh — do not edit, do not commit.
// The Filament fork tree this app links, resolved from native/filament.pin
// ($FILAMENT_COMMIT). \$(PLATFORM_NAME) picks the slice underneath it.
FILAMENT_TVOS_OUT = $FILAMENT_SRC/out/tvos-release
XCCONFIG

# ---- 4. the project ---------------------------------------------------------
xcodegen generate --spec "$TVOS/project.yml" --project "$TVOS" --quiet
